src/data/ACTIONS/ROLE.js, src/data/STATUSES/ROLE.js, src/data/STATUSES/SCH.js
This was missing when I was analysing SCH.
=> Add missing 'Cleric Stance' to shared role actions

src/utilities.js
Pretty self explanatory.
Simple utility functions that we talked in Discord about.
Here's a few examples:
```javascript
const values = [10, 0, 20, 30]
let value = 5
matchClosest(values, value) // 10
matchClosestLower(values, value) // 0
matchClosestHigher(values, value) // 10
```
```javascript
const values = {
0: "ignore",
10: "minor",
20: "medium",
30: "severe"
}
let value = 5
matchClosest(values, value) // ignore
matchClosestLower(values, value) // ignore
matchClosestHigher(values, value) // medium
```
=> Implement closestMatch utility

src/data/ACTIONS/WHM.js
Fixed the ID of Stone which was incorrectly set to the same value as Benediction :blobsweats:
=> Fixed the ID of Stone

src/data/STATUSES/PLD.js, src/parser/jobs/pld/FightOrFlight.js, src/parser/jobs/pld/index.js
Fight Or Flight analysis
* Tracks GCDs and Rotations during each FoF
* Checks if at least one Spirits Within and Circle of Scorn is being used under each FoF
* Checks that at least 2 Goring Blades are being used during FoF
* Ensures that FoF Goring Blades are at least 9 GCDs apart.
=> Fight Or Flight window analysis

src/data/ACTIONS/PLD.js, src/parser/jobs/pld/NOTES.md, src/parser/jobs/pld/Requiescat.js, src/parser/jobs/pld/index.js
Some tracking on how many missed Holy Spirits there are in Requiescat windows as well as listing the Requiescat windows and their rotations.
(Also there snuck a wrong ID through... :shipit:)
=> PLD Requiescat Module

config-overrides.js, package.json, src/data/ACTIONS/SAM.js, src/data/ACTIONS/WAR.js, src/data/ACTIONS/index.js, src/parser/core/modules/Cooldowns.js, yarn.lock
=> Shared Cooldowns - Addresses #7

src/parser/jobs/pld/About.js, src/parser/jobs/pld/FightOrFlight.js, src/parser/jobs/pld/Goring.js, src/parser/jobs/pld/Requiescat.js
=> PLD Quality Updates

src/parser/jobs/sch/Weaving.js, src/parser/jobs/sch/index.js
Subclassing the weaving module, and it's neat!
This should reduce the number of false positives of weaving issues - which really boil down to "don't use ruin 2"
=> SCH-specific suggestions for weaving

src/data/ACTIONS/MNK.js, src/data/ACTIONS/PGL.js, src/data/ACTIONS/index.js, src/data/STATUSES/MNK.js, src/parser/AVAILABLE_MODULES.js, src/parser/jobs/mnk/About.js, src/parser/jobs/mnk/Forms.js, src/parser/jobs/mnk/NOTES.md, src/parser/jobs/mnk/index.js
Super simple MNK analysis. Can be merged as-is or I can keep adding stuff from the NOTES. Very open to feedback on what I have in mind or things I might have forgotten about.
How do we track this? There's a game packet for meditative brotherhood procs but FFLogs doesn't use it
Maybe check for FBC being used at low GL when the next GCD gives a stack
=> Basic MNK analysis

src/parser/jobs/pld/Goring.js
More accurate DoT clipping for PLD as Goring refreshes after a Requiescat window have  1 less GCD before the refresh.
=> Consider Requiescat window for Goring refreshes

src/data/STATUSES/NIN.js, src/parser/jobs/nin/ShadowFang.js
Pretty much what it says on the box. I also added a duration property to the Shadow Fang status so there are fewer magic numbers flying around.
=> Switched the Shadow Fang module over to use tiered suggestions

src/parser/core/Entity.js
:blobmorning:
I adjusted the timestamp logic so it would do what it seems to have been intended to do (use the earlier timestamp between current and given).
=> Fixed the entity _statusFilter() logic

src/parser/jobs/whm/About.js
Switched my role for the WHM module to Maintainer for consistency.
=> Switch role

src/parser/core/modules/CooldownDowntime.js
=> fixed a small thing to make more sense

src/parser/jobs/nin/NinWeaving.js
It should still probably count as something bad, but that's for a separate module.
=> Fixed a bug wherein incomplete TCJ uses were counting as a bad weave

config-overrides.js, locale/en/messages.json, package.json, src/components/I18nLoader.js, src/parser/jobs/smn/Ruin4.js, yarn.lock
Also a fix for smn text because rolling two disparate things together is totally my style.
Should resolve #113
=> Intl polyfill

src/parser/jobs/whm/About.js
and added a bit to the description as well
=> WHM about localization

src/data/ACTIONS/MCH.js, src/data/ACTIONS/index.js, src/data/STATUSES/MCH.js, src/parser/AVAILABLE_MODULES.js, src/parser/jobs/mch/About.js, src/parser/jobs/mch/index.js, src/parser/jobs/mch/notes.md
Core data for actions/statuses, plus a basic About.js and a notes.md for MCH.
=> Initial MCH commit

src/parser/jobs/whm/Assize.js, src/parser/jobs/whm/Benison.js, src/parser/jobs/whm/DoTs.js
Assize is now a checklist item, and allows for holding it during downtime.
Benison severity reduced
DoT uptime now shows WARN between 90% and 95%
Also, Assize, Benison and DoTs are localized
=> WHM updates

src/parser/jobs/rdm/Procs.js
Just a small fix for Impactful threshold handling.  As well as some debug statements that've been commented out.
=> Fixed an issue with the impactful override never being disabled.

src/components/ui/TimeLineChart.js, src/data/ACTIONS/MNK.js, src/data/ACTIONS/index.js, src/data/STATUSES/MNK.js, src/data/STATUSES/SHARED.js, src/parser/jobs/mnk/Demolish.js, src/parser/jobs/mnk/Fists.js, src/parser/jobs/mnk/Forms.js, src/parser/jobs/mnk/GreasedLightning.js, src/parser/jobs/mnk/MnkAoE.js, src/parser/jobs/mnk/NOTES.md, src/parser/jobs/mnk/index.js
The change for the TimeChart should probably merge the default but idk Javascript. There's a bunch of TODOs in the MNK job modules, I mean to fix those in later PRs so this one should be good to go.
=> Add MNK DoT/Gauge uptime and basic AoE checks

src/parser/jobs/mnk/Fists.js, src/parser/jobs/mnk/GreasedLightning.js
Fixing stuff as requested in #143
=> Fix MNK useless guards and correct Tiered Suggestion values

src/data/ACTIONS/MCH.js, src/data/PETS.js, src/data/STATUSES/MCH.js, src/parser/jobs/mch/Turrets.js, src/parser/jobs/mch/index.js
_Holy crap it's something that isn't NIN-related._
=> Added a module for tracking MCH turret use

src/parser/jobs/rdm/Procs.js
Modified how I'm determining invulnerability checking for proc usage based on bug reports from Meru, Ari, and Tokata.
=> Resolved an issue with boss invuln and proc casting.

src/parser/jobs/mch/Turrets.js
Tidied up the null assumption handling code and added a check for Overdrive casts while I was at it. I don't expect that case to ever get hit in practice, but it shouldn't hurt anything.
=> Fixed the null assumption handling code for MCH turrets

src/parser/jobs/whm/Assize.js
Reduced the window of downtime check to within 1.5s after it's available.
=> quick fix for assize

src/data/STATUSES/MNK.js, src/parser/jobs/mnk/Fists.js, src/parser/jobs/mnk/GreasedLightning.js, src/parser/jobs/mnk/MnkAoE.js, src/parser/jobs/mnk/NOTES.md
These commits can probably be squashed, just a few fixes and a mostly-logical RoW analyser. Mainly pushing this to get my tree sorted for some bigger PRs I don't wanna mix changesets with.
=> Riddle of Wind checking and general cleanup

src/parser/jobs/drg/Weaving.js, src/parser/jobs/drg/index.js, src/parser/jobs/drg/notes.md
Just a small one for jump weaving. Also cleaned up notes.md while I was at it.
=> Added custom weaving logic for DRG

src/parser/jobs/ast/ArcanaTracking.js
Did not handle case where first action was a statusoff. Fixed for hopefully all other initial actions.
=>  Hotfix: Card tracking init state was choking on undraw actions.

src/parser/jobs/sam/About.js
4.4 is just pure potency increases, nothing about how the job works was changed in 4.4
=> Updated Support

src/parser/jobs/ast/About.js
This patch the planned updates are:
- Minor Arcana CD: This is just QoL and will let the player throw Crowns cards faster. No Processing affected.
- CU: This means they'll be able to weave CU faster if they only want it for the regens. No processing affected but may write some suggestion for this at a later date.
=> AST: version update.

src/parser/jobs/drg/About.js, src/parser/jobs/mch/About.js, src/parser/jobs/nin/About.js
No significant changes to any of these jobs, so they should be good to go.
=> Updated NIN, MCH, and DRG to support 4.4

src/data/STATUSES/ROLE.js, src/parser/jobs/ast/About.js
People actually use this now! And they even extend the buff! :(
=> Hotfix: E4E status entry

src/data/ACTIONS/MRD.js, src/data/ACTIONS/WAR.js, src/parser/jobs/war/Combos.js, src/parser/jobs/war/Gauge.js
This is rewrite of the gauge module. Instead of assuming the user has done every combo correctly, it now uses the `Combo` modules to only attribute `Rage` when the combo is done correctly. Also adds missed combos suggestion.
=> Rewrite of the Gauge module

package.json, src/data/ACTIONS/index.js, src/data/LANGUAGES.js, src/data/PETS.js, src/data/STATUSES/index.js, src/utilities.ts, yarn.lock
Having these functions that are used in many places correctly typed helps type inference get more types right.
=> Convert utilities.js to ts

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, src/parser/jobs/mch/modules/Heat.js
Look at me, I'm actually writing analysis code again.
=> Cooldown usage during post-overheat barrel lockout

src/parser/jobs/mnk/modules/Fists.js
This needs a bit of work later to adjust height/width stuff but so does GL3 so I think I'll try to do them at the same time. Easier to get this out now for maintenance.
=> Use core pie chart for Fists module

src/parser/core/modules/ChangeLog.js, src/parser/core/modules/ChangeLog.module.css, src/parser/core/modules/index.js, src/parser/jobs/smn/index.js
This is still a work in progress, but the only thing left for "feature-complete" is I believe, not rendering the module at all if there's no changelog property (old module format), or if it's empty.
=> Job Changelogs

src/data/ACTIONS/ROLE.js
Smol fix for a bug brought to light on Discord this morning.
=> Added missing properties to Break

src/parser/core/modules/Arcanum.js, src/parser/jobs/brd/modules/AdditionalStats.js, src/parser/jobs/brd/modules/PitchPerfect.js
- fixed wrong crit info from dots from FFLogs
- fixed arcanum not considering 'refreshbuff'
- fixed webpackChunkName :blobknife:
=> Fixed wrong crit from FFLogs and also some other minor fixes

src/parser/jobs/drg/modules/RotationWatchdog.js
Because I did not anticipate this particular flavor of people being bad.
=> Fixed a bug where DRGs who don't start with HT broke everything

src/parser/jobs/rdm/NOTES.md, src/parser/jobs/rdm/index.js, src/parser/jobs/rdm/modules/Dualcast.js
Minor PR
- Added a TODO from Nem and Ari discord pings
- Added last of RDM Localization tags I believe
- Modified Severity for DualCast Miss/Waste based on Feedback from RDMs
=> Last of Localization + Dualcast Severity modification

src/parser/jobs/rdm/index.js, src/parser/jobs/rdm/modules/Procs.js
Resolved issues being flagged by Sentry.  Targets missing in Omega(Story) and logs not having any of one or more RDM core procs.
=> Resolved issues with logs missing procs entirely, and invuln targets

src/parser/jobs/nin/modules/TrickAttackUsage.js
People in the Balance were commenting on it so I figured I should probably do this before I forget (I totally forgot, this was a week ago).
=> Smol severity tweak for Trick Attack usage

src/parser/jobs/mnk/modules/Fists.js
Also, fix a bug where stances can be negative or show at zero, mainly stanceless.
=> Add normaliser for pre-pull fists

src/parser/jobs/sam/modules/Buffs.js
Some people complained so I took upon myself to fix it.
Might take over the module, who knows.
=> Fix SAM early application suggestions, aka they shouldn't exist

src/parser/jobs/nin/modules/Ninjutsu.js
Nothing spooky, just what it says on the box.
=> Twiddled STD tiers as per suggestions from The Balance

src/data/STATUSES/PLD.js, src/parser/jobs/pld/index.js, src/parser/jobs/pld/modules/Goring.js
What it says on the tin. :shipit:
=> PLD Goring Update and Module Version match

src/parser/jobs/pld/modules/Cooldowns.js, src/parser/jobs/pld/modules/OGCDDowntime.js, src/parser/jobs/pld/modules/index.js
Implemented tracking for Spirits Within and Circle of Scorn cooldown downtimes.
Also sorted cooldowns in the timeline into reasonable groupings.
:shipit:
=> Added PLD oGCD tracking

src/parser/jobs/pld/modules/Requiescat.js
Matching sub 80% MP applications and let the player know they didn't apply a buff.
=> [PLD] Track failed Requiescat Buff windows

src/parser/jobs/pld/modules/Requiescat.tsx
If the MP during a Requiescat Window was within the MP Tick Amount Treshold, it would track it and generate extremely long rotations for it, regardless of the buff being actually applied.
This PR fixes this edge case.
=> [PLD] Fix occasional wrongly tracked Requiescat windo

locale/en/messages.json, src/parser/jobs/mch/index.js, src/parser/jobs/mch/modules/HotShot.js
=> Updated MCH for 4.5

src/data/ACTIONS/WHM.js, src/parser/jobs/whm/index.js
Yes, I know the branch name is wrong
=> update assize cooldown to be 45s instead of 60

src/data/ACTIONS/WHM.js, src/data/STATUSES/SHARED.js, src/parser/jobs/whm/index.js, src/parser/jobs/whm/modules/Assize.js
Let's wait till 4.5 drops so we can QA
=> 4.5 WHM: Assize cd buff yay!

src/parser/jobs/blm/modules/OGCDDowntime.js
I tested it with a whole 2 logs of my own and it looked sane. Also other jobs can use that as a template how to config their own stuff
=> config for BLM OGCDs as talked about with laqi

src/parser/jobs/blm/modules/Gauge.js
(Got it? Got it? :D??)
Previously a bug counted a killing blow on entities as a player death in gauge. Not anymore now
=> killing things is now less deadly for your log

src/parser/jobs/rdm/index.js, src/parser/jobs/rdm/modules/Gauge.js
Fixed the RDM gauge shenanigans by putting in floor protection before beginning calculations.
=> RDM Gauge Floor fix

src/parser/jobs/rdm/modules/GeneralCDDowntime.js, src/parser/jobs/sam/modules/Meikyo.js, src/parser/jobs/sch/modules/Aetherflow.js, src/parser/jobs/sch/modules/ClericStance.js, src/parser/jobs/sch/modules/DISPLAY_ORDER.js, src/parser/jobs/sch/modules/ShadowFlare.js, src/parser/jobs/sch/modules/Weaving.js
Except that one bit of DRK because half that module needs a logical/maths rethinking I guess. Commits separated by actual change and module so it's easier to inevitably fix something. Also I tested literally none of this but it's prob good.
=> Linter cleanup

src/data/PATCHES.ts
Is this the right way to push a PR to this project?
Known little about typescript ^ ^
=> add update time of CN 4.4 edition

src/parser/jobs/drk/modules/Buffs.js
Fix Grit tracking to infer Grit active since start of fight if Blood Price is used before seeing a "apply Grit" event
=> DRK Grit tracking fix

src/parser/jobs/blm/modules/RotationWatchdog.js
same thing in a new branch and with tiered suggestions
=> UI ending in T3

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/nin/modules/Ninki.js
Feature request from Kaede Akamatsu.
Local testing done. Mostly a copy-paste job from the DRK Blood implementation by Mike.
=> Implement Ninki resource graph.

src/data/ACTIONS/BLM.js, src/parser/jobs/blm/modules/Elements.js, src/parser/jobs/blm/modules/Gauge.js, src/parser/jobs/blm/modules/NOTES.md, src/parser/jobs/blm/modules/RotationWatchdog.js
Action definitions preliminary until we have real IDs and stuff, but at least calling modules can reference them...
=> BLM Gauge changes & action definition updates

src/parser/jobs/blm/index.js, src/parser/jobs/blm/modules/OGCDDowntime.js, src/parser/jobs/blm/modules/RotationWatchdog.js
=> Shb blm despair thunder

src/data/ACTIONS/DNC.js, src/data/ACTIONS/GNB.js, src/data/ACTIONS/MCH.js, src/parser/core/changelog.tsx, src/parser/core/index.tsx, src/parser/core/modules/GlobalCooldown.js
=> Add handling for longer-than-GCD cooldowns on GCDs

src/parser/jobs/drk/modules/BloodWeapon.tsx, src/parser/jobs/drk/modules/Delirium.tsx
This pull should be handled after #469
=> DRK adjust expected GCDs in BW/Delirium at end of fight

.circleci/check-extract.sh, .circleci/config.yml, locale/en/messages.json, src/parser/jobs/sam/index.js
too damn right i'm gonna
hey acc check how fucking atrocious my bash is
=> Watch while i break the build then fix it again

src/data/ACTIONS/ROG.js, src/parser/jobs/nin/index.js
HEY GUYS NIN IS FIXED NOW, FEELS GREAT TO PLAY AGAIN.
:|
=> Updated Gust Slash potency for 5.05

src/data/ACTIONS/MCH.js, src/parser/jobs/mch/index.js
Not really sure what the point of this change was, SE, but thanks I guess?
=> Reduced Reassemble recast for 5.05

src/parser/jobs/drg/index.js
=> Flagged DRG as supported for 5.05

src/parser/jobs/brd/index.js
=> Set BRD as 5.05 Supported

src/data/ACTIONS/AST.js, src/data/STATUSES/AST.js, src/parser/jobs/ast/index.tsx, src/parser/jobs/ast/modules/ArcanaTracking/ArcanaTracking.tsx
Should ideally be tested when the servers go up. Will need to source other's logs.
=> 5.05 AST Patch changes

locale/en/messages.json, src/data/STATUSES/AST.js, src/parser/jobs/ast/modules/ArcanaTracking/ArcanaTracking.tsx, src/parser/jobs/ast/modules/Cooldowns.tsx, src/parser/jobs/ast/modules/Lightspeed.js, src/parser/jobs/ast/modules/Sect/Sect.tsx
I don't need a changelog for this do I?
=> [BUGFIX] AST: Arcana pull states, Sect detection bug

src/parser/core/modules/Speedmod.js, src/parser/core/modules/Statistics/PieChartStatistic.tsx
These are just things ack told me to do to make other stuff work, prob both temporarily until core is fully typed, or at least these modules.
=> Smol typefixes

src/parser/jobs/pld/index.tsx, src/parser/jobs/pld/modules/FightOrFlight.tsx
No changelog update because just a version bump and a small internal thing that was never visible to anyone. :paissapeek:
=> PLD support updated to 5.05 + minor constant change in FoF module.

src/data/ACTIONS/BRD.js
I chose the ID for the group to be the same as Sidewinder for uniqueness
=> Add Sidewinder and Shadowbite to the same Cooldown Group

src/data/ACTIONS/DRG.js
=> [Bugfix] Flagged Coerthan Torment as a combo finisher

src/parser/jobs/mch/modules/Wildfire.js
=> [Bugfix] Fixed faulty Wildfire window logic

src/data/STATUSES/SCH.js
Just a small fix that adds Catalyze and adds a duration for statuses that lack them.
=> Update statuses for SCH

src/parser/jobs/dnc/modules/Technicalities.tsx
Any given window will now only give either the early or the late suggestion, not both. Also fixed a bug with pre-pull Devilments where the 'first use' was later than the cooldown but was still being marked as ok to happen pre-window.
=> Fixing some Devilment usage check bugs

src/data/ACTIONS/MNK.js, src/data/ACTIONS/PGL.js, src/data/STATUSES/MNK.js, src/parser/jobs/mnk/modules/Cooldowns.ts
What it says on the tin, new actions/statuses and setting the timeline. Not sure if duration on status is used in timeline, I never actually used it in the Forms module so changing `10000 => 15` isn't an issue there at least. If timeline ever used it, then I guess this fixes a wonky ass bug.
=> Shadowmonkers update data

src/parser/core/changelog.tsx, src/parser/core/modules/GlobalCooldown.js
Title.
cc @AkairyuGestalter 
fixes #534
=> Fix GCD duration normalisation for actions with a short recast

src/parser/core/changelog.tsx, src/parser/core/modules/AdditionalEvents.js
=> Fix actor filters for the AE query to use GUIDs

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/war/modules/InnerRelease.tsx
Update Warrior Inner Release module title from `Delirium`.
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>
=> Update Warrior Inner Release Module Title

src/parser/jobs/drg/modules/Buffs.js
Aesthetic bugfix, but bugfix nonetheless.
=> [Bugfix] Fixed the icon on one of the Dragon Sight suggestions

src/data/JOBS.ts
Match job colors to the values provided in fflogs.
- Update Dancer's job color to match the value given from fflogs.
- Remove TODO comments from Gunbreaker and Dancer jobs.
- Confirmation for Gunbreaker job.
=> Update Dancer and Gunbreaker Job Colors

src/parser/core/modules/RaidBuffs.js
=> Add devilment to raid buffs

src/parser/jobs/blm/index.js
=> no changes for blm in 5.08

src/parser/jobs/sch/index.js
No changes for SCH this patch.
=> Patch bump for SCH support to 5.08

src/parser/jobs/smn/modules/DoTs.js
No longer count the intentional DoT clip in the opener against the total clip time.
=> SMN DoT opener clip

src/parser/jobs/rdm/index.js
Just mark supported, no other changes.
=> Mark supported for 5.08

src/parser/jobs/dnc/index.tsx
=> mark dnc supported for 5.08

src/parser/jobs/pld/index.tsx, src/parser/jobs/pld/modules/FightOrFlight.tsx
Report: https://xivanalysis.com/analyse/AxLYBGh9Dz3ywaNX/1/67
Window of note: 
Live suggestions: 
New suggestions:
=> [PLD] Don't penalize for rushed FoF windows.

src/parser/jobs/whm/index.js
=> WHM 5.08 version bump

src/parser/core/modules/Weaving.d.ts, src/parser/jobs/smn/index.js, src/parser/jobs/smn/modules/Weaving.ts, src/parser/jobs/smn/modules/index.js
title
gonna sleep now, feel free to merge and shit if it looks 'aite
also includes a rudimentary `.d.ts` for core weaving because eh
=> Permit triple weave when summoning phoenix

src/parser/jobs/mnk/modules/Steppies.tsx
=> Deal with Kihra pulling event types out from under Boot

src/data/ACTIONS/AST.js
=> Fix action IDs for Aspected Benefic/Helios

src/parser/jobs/blm/index.js, src/parser/jobs/blm/modules/RotationWatchdog.tsx
Pre-pull buff update goobered our check for the first real cycle, so deal wit it
=> Fix opener checks for BLM

src/data/ACTIONS/SCH.js
Like it says on the ~~tin~~ title
=> Add Catalyze as a valid status for timeline support

src/parser/jobs/blm/modules/RotationWatchdog.tsx
Yes, hello, is this action speaking?
=> Fix BLM Sentry error

src/parser/jobs/ast/index.tsx, src/parser/jobs/ast/modules/ArcanaTracking/ArcanaSuggestions.tsx
Astros never make bug reports :(
=> [BUGFIX] AST: Self-carding does not display

src/data/PATCHES.ts
October 15, 2019 4pm UTC+8 according to this: http://ff.sdo.com/web8/index.html#/newstab/newscont/310730
=> update CN 5.0 patch date

src/data/PATCHES.ts, src/parser/jobs/blm/index.js, src/parser/jobs/dnc/index.tsx
Also add data/PATCHES definition to make TS happy
=> Core, BLM and DNC patch bump to 5.1

src/data/ACTIONS/DRG.js, src/data/ACTIONS/MCH.js, src/parser/jobs/drg/index.js, src/parser/jobs/mch/index.js
Figured I'd throw this one into the pot real fast before I work on the monstrosity that will be the NIN changes.
=> Small data changes to get DRG and MCH updated for 5.1

src/parser/jobs/sch/modules/Aetherflow.js, src/parser/jobs/sch/modules/Interrupts.js
With this, SCH should be ready for the upcoming changes to hooks.
=> Rename addHook in SCH modules to addEventHook

src/data/ACTIONS/RDM.js, src/data/STATUSES/RDM.js, src/parser/jobs/rdm/index.js, src/parser/jobs/rdm/modules/Gauge.js, src/parser/jobs/rdm/modules/GeneralCDDowntime.js
=> general updates to 5.1.  manafication fix

src/parser/jobs/nin/modules/Ninjutsu.js
=> [Bugfix] Fixed a small derp in the Ninjutsu module

src/data/ACTIONS/MNK.js, src/data/ACTIONS/SAM.js
Prob relevant to @Rjb99 too, this requires 5.1 so worth noting when we flag the jobs supported
=> Antman meditates on the GCD, feat. Samurai

src/parser/jobs/nin/modules/Ninjutsu.js
This is just a fix for CLIENT-18N and CLIENT-18P. Looks like there's some issues with weaving, but they're not causing crashes so that's 'aite-er.
cc @Toastdeib
=> Feex error in NIN

src/parser/jobs/mnk/index.tsx, src/parser/jobs/mnk/modules/Fists.tsx
And minor bug fixes to Fists chart.
=> Support MNK in Shadowbringers

src/data/ACTIONS/root/ARC.ts, src/data/ACTIONS/root/AST.ts, src/data/ACTIONS/root/BLM.ts, src/data/ACTIONS/root/BRD.ts, src/data/ACTIONS/root/DNC.ts, src/data/ACTIONS/root/DRG.ts, src/data/ACTIONS/root/DRK.ts, src/data/ACTIONS/root/GNB.ts, src/data/ACTIONS/root/LNC.ts, src/data/ACTIONS/root/MCH.ts, src/data/ACTIONS/root/MNK.ts, src/data/ACTIONS/root/MRD.ts, src/data/ACTIONS/root/NIN.ts, src/data/ACTIONS/root/PGL.ts, src/data/ACTIONS/root/PLD.ts, src/data/ACTIONS/root/RDM.ts, src/data/ACTIONS/root/ROG.ts, src/data/ACTIONS/root/ROLE.ts, src/data/ACTIONS/root/SAM.ts, src/data/ACTIONS/root/SCH.ts, src/data/ACTIONS/root/SMN.ts, src/data/ACTIONS/root/WAR.ts, src/data/ACTIONS/root/WHM.ts, src/data/ACTIONS/type.ts, src/parser/core/modules/PrecastStatus.js, src/parser/core/modules/Statuses.js
=> Port action statusesApplied to data keys for better layer compat

src/data/PATCHES.ts
KR already updated v5.08 balance
=> Fix KR patch date to v5.08

src/data/ACTIONS/root/BLU.ts, src/parser/jobs/blu/changelog.tsx
- add gcdRecast field to all gcd spells with cooldown times
=> Fix BLU's ABC Problems

src/data/ACTIONS/root/AST.ts, src/data/ACTIONS/root/DNC.ts, src/data/ACTIONS/root/GNB.ts, src/data/ACTIONS/root/MCH.ts, src/data/ACTIONS/root/MNK.ts, src/data/ACTIONS/root/NIN.ts, src/data/ACTIONS/root/ROLE.ts, src/data/ACTIONS/root/SCH.ts, src/data/ACTIONS/root/WAR.ts
because estimation is easier the more correct your source data.
=> Added charges data to skills that have them.

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/smn/index.js, src/parser/jobs/smn/modules/DoTs.js
For all fights, but especially those with multiple targets (E1S, E4S, TEA).
=> Improved display of SMN dot table

src/data/ACTIONS/root/PLD.ts, src/parser/jobs/pld/modules/OGCDDowntime.tsx
Went with the 15 seconds initial delay per conversation in #dev-tank
=> Update Intervene to be a charge skill, adjust CDDT params accordingly

src/parser/jobs/sch/index.js
Your friendly neighborhood Nono submitting support for SCH 5.2 support – there were no changes, so you know I worked so hard 😄
=> SCH support for 5.2

src/parser/jobs/mch/index.js, src/parser/jobs/nin/index.js
Job changes? What job changes?
=> Mark NIN and MCH as supported for 5.2

src/parser/jobs/blm/index.js, src/parser/jobs/dnc/index.tsx
=> Bump BLM and DNC to 5.2

src/parser/jobs/smn/index.js
No changes to analysis for 5.2
=> Updated SMN to 5.2.

locale/en/messages.json, src/parser/jobs/whm/modules/DoTs.js
Dia early refresh suggestion was broken and wouldn't show up because of the _lastApplication logic--fixed it so the suggestion works again
=> Fix WHM dia clipping suggestion

src/parser/core/modules/NormalisedEvents.ts, src/parser/jobs/mnk/modules/Steppies.tsx
Per comment on the original normalisedX migration PR and convo on Discord.
=> Add crit and DH count to normalisedevent interface

src/parser/jobs/sam/modules/AoeChecker.js
Ryan missed ~~Rage of Halone~~ an uppercase E
=> Feex master builds for prod deployments

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/whm/index.js, src/parser/jobs/whm/modules/Interrupts.js, src/parser/jobs/whm/modules/index.js
Pretty much what it says on the tin.
=> Add interrupt tracking to WHM

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/smn/index.js, src/parser/jobs/smn/modules/Devotion.js
Adds a suggestion whenever a Devotion cast fails to hit all players
=> Smn Devotion Suggestion

src/data/ACTIONS/root/SCH.ts, src/parser/jobs/sch/index.js, src/parser/jobs/sch/modules/Pets.js, src/parser/jobs/sch/modules/index.js
* Modify SCH actions to have the correct URL for Seraphic Veil
* Add SchPets class that extends PetTimeline
* Cry because my example parse shows me only using a single consolation during the seraph window
=> Add pet tracking module to SCH

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/core/modules/BuffWindow.tsx, src/parser/core/modules/Swiftcast.tsx, src/parser/jobs/sch/modules/Swiftcast.js, src/parser/jobs/smn/modules/Swiftcast.js, src/parser/jobs/smn/modules/index.js, src/parser/jobs/whm/modules/Swiftcast.js
* Remembered to run `yarn extract` first this time
* Modified `BuffWindow` to export `BuffWindowExpectedGCDs` interface so I can be a good person and annotate correctly.
* Modify SCH and WHM implementations of Swiftcast to use new core module
* Add Swiftcast tracking to SMN
=> Add Swiftcast tracking to core

src/data/ACTIONS/layers/index.ts, src/data/ACTIONS/layers/patch5.1.ts, src/data/ACTIONS/root/ARC.ts, src/data/STATUSES/root/BRD.ts, src/parser/jobs/brd/changelog.js, src/parser/jobs/brd/index.js, src/parser/jobs/brd/modules/Barrage.js, src/parser/jobs/brd/modules/Cooldowns.js, src/parser/jobs/brd/modules/index.js
I'm not gonna support BRD, but went to update Straight Shot Ready for issue #317 and figured I may as well do the rest. We don't use layers enough. Sidewinder module is insane but it surprisingly needed no changes.
=> 5.2 berd is the werd

src/data/ACTIONS/index.ts, src/data/STATUSES/index.ts, src/parser/core/modules/Statistics/index.ts, src/parser/core/modules/Timeline/components/index.ts, tsconfig.json
=> [skip ci] Enable isolated modules

src/fflogs.ts, src/parser/core/modules/NormalisedEvents.ts, src/parser/jobs/nin/modules/TrickAttackWindow.js
Add apply/remove debuff to NormalisedEvents to support Trick Attack in cases with many mirrored boss actors
=> [BugFix]: Normalise debuff events - fix TA windows gone wild

package.json
i'm using his remote though because i'm nice like that
=> PR lingui config fix cus furst didn't

src/parser/core/modules/UnableToAct/statusIds.ts, src/parser/jobs/blm/modules/NotCasting.js
Fixed the IDs used in UnableToAct.js and also adjusted NotCasting.js to not penalize you for being stunned etc
=> I fixed things in UnabletoAct and NotCasting

src/components/Find/FightItem.js
=> [BugFix]: Find page formatDuration throws

locale/en/messages.json, src/parser/jobs/sch/modules/DoTs.js
=> There's a typo in SCH's DoT warning

src/utilities/strings.ts
I swear, I do know how to code.
=> [BugFix]: formatDuration - precision should cause fixed decimal

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/sch/index.js, src/parser/jobs/sch/modules/Recitation.js, src/parser/jobs/sch/modules/index.js
Also ran `yarn extract` up front and even updated the changelog!
=> Add recitation vizualization to SCH

src/parser/jobs/sam/modules/Tincture.js, src/parser/jobs/sam/modules/index.js
Look at Nono, popping up in the DPS section now. I'm adding this because it was requested of me in the #sam_lounge
=> Add tincture use to SAM

src/components/LegacyAnalyse/Analyse.js, src/components/ReportFlow/ActorList.tsx, src/components/ReportFlow/Analyse.tsx, src/parser/AVAILABLE_MODULES.ts, src/parser/Conductor.ts, src/parser/core/Parser.tsx, src/parser/core/__tests__/Module.js, src/parser/core/__tests__/Parser.js
title. putting this up now but not merging until tomorrow, i'm looking at the diff and it's literally swimming. fucking hell.
- wires the new report shit down to the parser
- does a bit of refactoring on the way through, i think?
- i re-keyed AVAILABLE_MODULES.JOBS by job key instead of fflogs strings so that's a nice start on splitting it off nice and shit
supposing this gets merged and _isn't_ actually a fucking fever dream conjured up by my brain at 1am, next up will be consuming the new shit from core modules.
=> Wire new reports through to the parser framework

locale/en/messages.json, src/parser/jobs/sam/modules/Kaiten.js
please merge this the wording is seriously disrupting my samurai training
=> SAM - clean up kaiten wording

src/parser/jobs/sch/index.js, src/parser/jobs/sch/modules/Tincture.js, src/parser/jobs/sch/modules/index.js
What it says on the tin – pretty cut and dry, but not so dry you, like, choke on it or anything.
=> Add pots to SCH

docs/composing-job-analysis.md
=> Typo in composing-job-analysis.md

src/components/App.js, src/components/Home/ReportRedirect.tsx, src/components/Home/ReportSearch.tsx, src/components/Home/parseInput.ts
=> Add route for automatic redirection of incoming log urls

locale/en/messages.json, src/parser/core/modules/AoEUsages.tsx, src/parser/jobs/drk/modules/MultiHitSkills.ts, src/parser/jobs/mch/modules/MultiHitSkills.ts, src/parser/jobs/war/modules/MultiHitSkills.ts
@AzariahAeroborn @KelosPelmand
=> DRK / MCH / WAR - AoEUsages consistency

src/data/ACTIONS/layers/patch5.3.ts, src/data/ACTIONS/root/BRD.ts, src/parser/jobs/brd/changelog.js, src/parser/jobs/brd/index.js
Depends on: https://github.com/xivanalysis/xivanalysis/pull/987
=> BRD - 5.3 support

src/parser/jobs/sam/index.js
The Sam changes this patch were so long it's a miracle I could bump SAM up before 5.3 dropped.
=> updated SAM to 5.3

src/parser/jobs/blm/index.js
Patch bump for BLM, no job changes
=> BLM 5.3 patch bump

src/parser/jobs/smn/index.js
Potency change does not affect analysis.
=> Mark SMN as supported for 5.3

src/parser/jobs/rdm/index.js
update bump for RDM to 5.3 since no class changes in patch.
=> update to support patch 5.3

src/parser/jobs/whm/index.js
Since there's no functional changes, this should be okay.
=> WHM 5.3 support

src/parser/core/modules/PrecastStatus.js
Given that this is effecting several jobs and that #1008 had to implement a workaround for this, I went ahead and pulled this out as just a bugfix so that my testing cleanup in #905 doesn't hold up getting this bug fix in.
Which of course I should have done to begin with but the TS rewrite was so simple and then the testing felt pretty straightforward and then and then... 🙄
=> [BugFix] PrecastStatus - synthesize actions if an applybuff event occurs without cast

src/parser/core/modules/EntityStatuses.ts
Fixes this DNC bug and likely some others throughout the parser.
=> bugfix - statuses can't end later than the end of the fight

src/data/CONTRIBUTORS.ts, src/parser/jobs/brd/index.js, src/parser/jobs/brd/modules/Barrage.js, src/parser/jobs/brd/modules/DISPLAY_ORDER.ts, src/parser/jobs/brd/modules/PitchPerfect.js, src/parser/jobs/brd/modules/Sidewinder.js, src/parser/jobs/brd/modules/Snapshots.tsx
- Remove the "early stages" warning, bard coverage is fairly complete at this point
- Add myself as bard maintainer since there isn't one right now
- Add a sensible module display order
=> BRD - Housekeeping

src/parser/jobs/drg/modules/BattleLitany.tsx
Old logic figured that if a Battle Litany buff ended early it was caused either by the end of the fight or by another player, completely overlooking the fact that if you die, the buff also ends early. Marks open windows on death with a flag that excludes it from the overlap check.
Could use some extra tests on this; I found like 3 logs and checked both the overlap and death cases, but there might be a few corner cases that were overlooked.
=> DRG: Fix for Battle Litany Module Counting Death as Overlap

README.md
Start with a simple change, and then we can figure out if we want to add something to the i18n docs page or otherwise.
=> add link to CrowdIn in README.md

src/utilities/random.ts, yarn.lock
More where this came from, just getting the easy ones that don't need code changes out of the way.
=> Minor version bumps

src/parser/jobs/mch/modules/Tincture.tsx, src/parser/jobs/mch/modules/index.js
https://github.com/xivanalysis/xivanalysis/pull/1015#discussion_r511545566
=> Rename MCH Tincture import alias

src/data/ACTIONS/layers/patch5.1.ts
Changed Collective Unconscious's cooldown from 90s to 60s (as it currently is in-game)
=> Update AST.ts with correct Collective Unconscious cooldown

src/parser/jobs/blm/index.js, src/parser/jobs/dnc/index.tsx
=> Mark BLM and DNC as supported for 5.4

src/parser/jobs/ast/index.tsx
No AST changes were published in the preliminary patch notes
=> Update AST to indicate 5.4 support

src/parser/jobs/pld/index.tsx
No actual change was needed. This just version bumps (and fixes the sorting of the changelog).
=> Pld 5.4 support

src/data/BOSSES.ts, src/parser/AVAILABLE_MODULES.ts, src/parser/bosses/e9/index.ts, src/parser/bosses/e9/modules/Invulnerability.ts, src/parser/bosses/e9/modules/index.ts
Not too hard. I totally still have sanity left.
* Create directory / file scaffolding for e9 under `parser/bosses`
* Wander into this nicely marked ~~maze~~ path to quickly find the boss ID
* Update the tau for boss to firsttap until overkill
* Reload the page dozens of times wondering why it isn't working
* Realize I need to import all this somewhere.
* Descend into the third ~~layer of the labyrinth~~ file of AVAILABLE_MODULES and find the right section to add
* Find the right section in `data/bosses` and guess at the ID
* Get the ID right
* Perform PR
=> Bend time(line) to my will, recognize TAU for e9s

src/parser/core/modules/PrecastStatus.js
Fixes issues reported in these logs:
https://xivanalysis.com/fflogs/byLkCfRQDPxg4Fht/4/34
https://xivanalysis.com/fflogs/y4gQ1J9Vq7LYWtfp/13/8
https://xivanalysis.com/fflogs/GcNF4vBnMZYtTpCr/22/7
https://xivanalysis.com/fflogs/GcNF4vBnMZYtTpCr/12/7
See https://discord.com/channels/441414116914233364/470049935077933076/789239198691360829 and following
=> fix: sort events before PCS normalise

src/components/ui/DbLink.tsx, src/components/ui/I18nMenu.js, src/store/i18n.ts
Title.
Since the developer won't take the advantage.
Not so hard, is it?
Smile.
=> Use cafemaker for CN game language tooltips

src/parser/core/modules/SpeedmodConsts.js
Leaving BRD shit alone mostly, Huton could prob fab events like how GL does even if it's a bit more complex.
=> Cleanup SpeedmodConsts and remove Blood Weapon from it

src/parser/core/modules/PetTimeline.tsx, src/parser/jobs/mch/index.tsx, src/parser/jobs/mch/modules/Cooldowns.js, src/parser/jobs/mch/modules/QueenTimeline.ts, src/parser/jobs/mch/modules/index.ts
=> MCH - Add queen actions to the timeline

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/pld/index.tsx, src/parser/jobs/pld/modules/FightOrFlight.tsx, src/parser/jobs/pld/modules/Tincture.tsx, src/parser/jobs/pld/modules/index.tsx
Adds a tincture module with 13 required GCDs and 1 use of sw/soc per pot.
=> PLD - Tinctures

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/pld/index.tsx
Fixes an issue with the intro/overview text for PLD where skill links were broken.
=> Pld copy fix

src/data/ACTIONS/type.ts, src/data/__tests__/getDataBy.ts, src/data/getDataBy.ts, src/parser/core/modules/Cooldowns.ts, src/parser/core/modules/PrecastStatus.js, src/parser/jobs/ast/modules/Cooldowns.tsx, src/parser/jobs/brd/modules/Cooldowns.js, src/parser/jobs/drg/modules/Cooldowns.js, src/parser/jobs/drk/modules/Cooldowns.ts, src/parser/jobs/gnb/modules/Cooldowns.tsx, src/parser/jobs/mch/modules/Cooldowns.js, src/parser/jobs/mnk/modules/Cooldowns.ts, src/parser/jobs/nin/modules/Cooldowns.js, src/parser/jobs/pld/modules/Cooldowns.tsx, src/parser/jobs/smn/modules/Cooldowns.js, src/parser/jobs/war/modules/Cooldowns.ts, src/reportSources/legacyFflogs/eventAdapter/prepullStatus.ts
(and clean it up a bit)
i was going to port it across to the analyser system while i was at it but i totally missed one of the dependencies which is actually a massive tree of downtime related stuff that will be total hell to deal with. so it's gonna wait a bit.
=> Port cooldowns to TS

src/parser/jobs/brd/index.js, src/parser/jobs/dnc/index.tsx, src/parser/jobs/mch/index.tsx
=> Patch 5.5 support for phys. ranged

src/data/ACTIONS/layers/index.ts, src/data/ACTIONS/layers/patch5.5.ts, src/parser/jobs/drk/index.tsx, src/parser/jobs/gnb/changelog.tsx, src/parser/jobs/gnb/index.tsx, src/parser/jobs/war/index.tsx
What it says on the tin. Got a bug fix for pre-5.3 WAR but leaving to another PR. Depends on #1136.
=> Patch 5.5 support for WAR, DRK, and GNB

src/parser/jobs/blm/index.js
=> Mark BLM as supported for 5.5

locale/en/messages.json, src/data/ACTIONS/layers/patch5.5.ts, src/parser/jobs/drg/index.js
Just potency changes again. Also, a typo fix.
=> DRG: patch 5.5 support

src/parser/jobs/nin/index.js
No changes to the job this patch. \o/
=> Marked NIN as supported for 5.5

src/parser/jobs/sam/index.js
Much like my Social Life in the last year, nothing has changed.
=> Sam Bump to 5.5

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/jobs/gnb/changelog.tsx, src/parser/jobs/gnb/modules/Tincture.tsx, src/parser/jobs/gnb/modules/index.tsx
As requested by balance tank_tc. Requires at least 1 blasting zone and 1 GF combo per tincture, which should pretty much always be achievable.
=> GNB - Tinctures

locale/de/messages.json, locale/en/messages.json, locale/fr/messages.json, locale/ja/messages.json, locale/ko/messages.json, locale/zh/messages.json, src/parser/core/modules/UnableToAct/UnableToAct.tsx
title. had >0 errors come through from this which were just funky logs.
=> Move UTA window error to brokenLog trigger

src/parser/core/modules/CooldownDowntime.tsx, src/parser/core/modules/Cooldowns.ts, src/parser/core/modules/Downtime.tsx, src/parser/core/modules/GlobalCooldown.js, src/parser/jobs/brd/modules/AlwaysBeCasting.ts, src/parser/jobs/brd/modules/PitchPerfect.js, src/parser/jobs/brd/modules/SongUptime.js, src/parser/jobs/brd/modules/Util.js, src/parser/jobs/dnc/modules/DirtyDancing.tsx, src/parser/jobs/dnc/modules/Procs.js, src/parser/jobs/drg/modules/BloodOfTheDragon.js, src/parser/jobs/drg/modules/Drift.tsx, src/parser/jobs/drg/modules/Procs.js, src/parser/jobs/mch/modules/Drift.tsx, src/parser/jobs/mnk/modules/Forms.tsx, src/parser/jobs/nin/modules/TrickAttackUsage.js, src/parser/jobs/rdm/modules/Dualcast.js, src/parser/jobs/rdm/modules/Procs.js
Title. Unlike invuln, no major changes here. just pushing the time translation down a layer.
=> Port downtime to analyser

src/reportSources/legacyFflogs/eventAdapter/adapter.ts, src/reportSources/legacyFflogs/eventAdapter/oneHpLock.ts
Title. Not going to sit on this one, given prod is broken.
=> Add OneHpLock adapter step

src/parser/jobs/blm/modules/RotationWatchdog.tsx
Boolean logic after a shit day at work is hard
=> BLM BugFix: JP Opener Expected F4 Count

src/reportSources/legacyFflogs/eventAdapter/translate.ts
3/3 sentries so far that have tripped this have been failed hits (MISS or IMMUNE)
=> [Bugfix]: Whitelist failed hits for adapting unpaired damage events

src/reportSources/legacyFflogs/eventAdapter/translate.ts
=> Bugfix: Mark RESIST as a failed hit

src/reportSources/legacyFflogs/eventAdapter/translate.ts
Title. Sets are fun. Also minor tweaks to style because I'm anal.
=> Make null-sequence sanity check zoomier

src/parser/jobs/sam/modules/Kenki/Kenki.js
2 years later and Yukikaze is finally getting that extra 5 kenki from 5.0
=> [Sam] Fix wrong Yukikaze amount

src/reportSources/legacyFflogs/eventAdapter/speedStat.ts
I probably shouldn't have moved all that event handling to the adapt pass at oh-dark-thirty.
=> fix speedStat so it sees precastStatus events

src/parser/core/modules/Actors/Actor.ts, src/parser/core/modules/SpeedAdjustments.ts, src/parser/core/modules/index.js, src/utilities/speedStatMapper.ts
This is just a minimal scaffold for a speed adjustments module so we've got an API to build against. Further work at a later date will be required to hook this up with proper tracking and suchforth.
I don't expect this will be the final full API - helper methods and additional parameters will no doubt be needed as usecases grow.
This also wires up the new attributes data into the actors module.
=> Add rudimentary speed adjustments module

src/reportSources/legacyFflogs/eventAdapter/speedStat.ts
=> Fix speedStat adapter handling of status reapplication

src/parser/core/modules/Timeline/components/Timeline.module.css
title. dunno when these broke. probably some recent tooling update or something.
=> Fix timeline collapse markers

src/parser/core/modules/Cooldowns2.tsx
=> Remove CD2 debug

src/data/PATCHES/patches.ts
=> Add patch dates for CN 5.4 and 5.5

src/fflogs.ts, src/parser/jobs/brd/modules/AdditionalStats.js, src/parser/jobs/brd/modules/ApexArrow.tsx, src/parser/jobs/brd/modules/PitchPerfect.js, src/parser/jobs/brd/modules/Sidewinder.js, src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
FFLogs updated its API, let's get rid of this field
=> Remove debugMultiplier

src/parser/jobs/smn/modules/Weaving.ts
=> Fix smn weaving bug

src/parser/core/modules/BuffWindow.tsx
=> Add 1s fudge to buff window status duration

src/parser/core/modules/BuffWindow.tsx
=> fudgy buff window, now with 100% more null checking

src/parser/jobs/drg/modules/Buffs.tsx
apparently #1277 had a partial version of this file in my commit, my b.
this should resolve the dependencies, could use a sanity check it's late for me
=> DRG: Actually port buffs to analyser

src/parser/jobs/mnk/modules/Weaving.ts
two lines code, eight lines comment. nice.
acc'll hate this.
pls2read the comment :)
=> Fix over-eager weaving warnings on MNK

src/parser/jobs/ast/modules/ArcanaUndrawUsage.tsx
I cleaned up some redundant code while I was here.
=> AST - Undraw fix

src/utilities/isSuccessfulHit.ts
Pulling this out of the MCH gauge PR since that needs some rethinking. cc @AzariahAeroborn
=> isSuccessfulHit fix

src/data/ACTIONS/root/MCH.ts
* Heat Blast / Auto Crossbow aren't affected by sks
* Roller Dash (the pet action) is affected by sks; consequences unclear
=> MCH - speedmod updates

src/parser/core/modules/ActionWindow/windows/BuffWindow.ts, src/parser/jobs/drg/modules/DragonSight.tsx
drg module maintainer was on the floor during the original PR review whoops
Let BuffWindow accept a Status[] again and updated the Dragon Sight module to use the BuffWindow module better.
=> core: let BuffWindow accept Status[]

src/parser/jobs/drk/modules/BloodGauge.tsx
=> DRK - Remove private Data dependency from Blood Gauge

src/parser/jobs/mch/modules/Hypercharge.tsx
I did something dumb and we merged in a bug. I rewrote the logic to just use core History so that next time if something goes wrong I have deniability :)
=> MCH - Hypercharge uses History class now

src/parser/jobs/drg/modules/BloodOfTheDragon.tsx
quick fix for timestamp formatting in botd module
=> DRG: fix botd module timestamps

src/data/ACTIONS/root/RPR.ts, src/data/STATUSES/root/RPR.ts, src/parser/jobs/rpr/changelog.tsx
Attributes might be incorrect, I went off of weaponskill vs spell. Combos are stubbed as we don't know the IDs yet.
=> Stub RPR data
