- src/parser/jobs/war/Gauge.js
- Fixed a typo that was causing Storm's Path not to be read.
- Added warning about the lack of accuracy for gauge-tracking method.
> Fixed a little bug, added a warning.

- src/data/STATUSES/NIN.js
- src/parser/jobs/nin/Duality.js
- src/parser/jobs/nin/Ninjutsu.js
- src/parser/jobs/nin/Ninki.js
- src/parser/jobs/nin/TrickAttackWindow.js
- src/parser/jobs/nin/index.js
- src/parser/jobs/nin/todo.txt
This NIN update includes a module for tracking Dream Within A Dream usage outside of Trick Attack windows and Armor Crush usage in them, as well as module for tracking Duality usage on any non-Aeolian Edge GCDs. I also tidied up a couple of things here and there to keep the code as clean and consistent as possible.
> Two new modules for NIN and minor cleanup

- README.md
- src/parser/core/Module.js
- src/parser/core/Parser.js
* Better name for the data gathering function
* Default no-op implementation of the function with JSDocs
* Document the function in README
* Add a couple more tags to reports
* Add all this stuff to `output()` errors as well as event hook errors.
> More Error Context!

- src/data/ACTIONS/NIN.js
- src/parser/jobs/nin/Ninki.js
- src/parser/jobs/nin/todo.txt
Update to the Ninki module - it now yells at you for using Hellfrog on single targets when you have Bhava and/or TCJ available for use. 1-2 uses is flagged as minor, since there are some legitimate excuses (e.g. lots of movement for mechanics so you can't pop TCJ).
> Added Hellfrog misuse to the Ninki module and reordered functions a bit

- locale/en/messages.json
- package.json
lingui's extractor is still a bit weird, and it can cache outdated English locale strings. To fix that, this commit just changes the extract command to entirely delete and re-add the en locale.
This might need to change in the future depending on how we set up localization of actions and the like, but it should work for now.
> Fix English i18n Desync

- src/index.js
Forgot this was an option when I was setting things up. All our JavaScript loads from `xivanalysis.com/static/ ` so we may as well just whitelist that specific path to cut out more of the junk from browser extensions and other weird situations.
> Add url whitelisting for Sentry

- package.json
- yarn.lock
This uses the modules `husky` and `lint-staged` to run `eslint --fix` on all staged files match `src/**/*.js`. It should stop people from commiting code with syntax errors and also apply style tweaks for people that don't have their editors doing it on save.
> Create a pre-commit linting hook

- jsconfig.json
Changed the jsconfig.json to only include /src/**/* as it's scope so auto-fill/intellisense doesn't spend years to load.
> Scope VS code project to /src

- src/parser/jobs/rdm/GeneralCDDowntime.js
Ari informed me my understanding of SwiftCast was mistaken and that it should be used as soon as pretty much any proc slot was available, instead of only to fish for procs when no procs were available.  As such I have added it to the tracked CDs for RDMs
> Added SwiftCast to tracked CDs after discussion with Ari

- src/parser/jobs/nin/NinWeaving.js
If this seems a bit goofy, I'm open to better suggestions. Ideally we wouldn't need this but bad data is bad data.
> Added DWaD de-duping sauce to the NIN weaving module

- src/components/I18nLoader.js
- src/components/ui/DbLink.js
- src/components/ui/I18nMenu.js
- src/data/LANGUAGES.js
- src/store/actions.js
- src/store/index.js
- src/store/reducers.js
- src/utilities.js
This PR sets up automatic language detection using `navigator.languages`, and it additionally updates the format for language data in the redux store so that we can hopefully do more complex things in the future. I want to eventually add a setting to let users specify their preferred game language to show actions, etc. in that rather than their site language.
This also listens for an language change events to respond to them. Probably not anything that'll happen with any sort of frequency, but it's almost effortless so we may as well.
> Automatic Language Detection

- package.json
Husky currently changes your staged changes and commits whatever it feels like without any user input. It's annoying but also breaks `git add --patch` via the `git add` at the end. This PR removes the auto add and sets the commit to fail if linting doesn't pass, while still applying the fixes for the user to review. I don't know how this comment turned out so long.
> Fix lint-staged

- src/components/ui/GlossaryTerm.js
- src/components/ui/GlossaryTerm.module.css
- src/components/ui/TransMarkdown.js
- src/data/GLOSSARY.js
This PR accomplishes two things.
1. Define a `<GlossaryTerm />` tag for defining terms that might need to be explained for users, with tooltips on hover that are formatted with markdown and support i18n.
2. Extend `<TransMarkdown />` to do special rendering for markdown links, allowing us to inject custom content such as `<GlossaryTerm />`s, `<ActionLink />`s, and `<StatusLink />`s.
The custom link renderer seems to break reference-style links in markdown, but those are probably never going to actually be used so it doesn't really matter.
> Glossary Terms and More Powerful Markdown

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- package.json
- public/index.html
- src/components/ui/DbLink.js
- src/components/ui/DbLink.module.css
- yarn.lock
This PR implements `<DbLink />` in React. It performs better and updates more reasonably when something like the current language changes. It:
* Creates a XIVDBTooltipProvider class that handles debouncing and caching requests to be nice to XIVDB's API.
* Rewrites the `<DbLink />` component to use that provider and to format its own output.
* Removes the script tag loading the existing XIVDB tooltip JS library.
Behavior is slightly different. Rather than following your mouse cursor, the tool-tip that appears (which is implemented via Semantic UI's `<Popup />`) has a static position somewhere around the link that it will be fully visible.
> Rewrite <DbLink /> to ditch the XIVDB Tooltip JS Library

- src/parser/core/modules/Invulnerability.js
This PR tweaks the event filter used when guessing invuln periods.
- Fixed stupid mistake that was preventing heal filter from working
- Expanded heal to _exclude_ self-heals
- Added `begincast` event filter that uses same check as heal
These changes do make it a little _too_ lax about downtime, but it's the difference between being hyper trigger happy and a _bit_ too lax, which... well, it's better, i guess.
**Before (Guardian):**
**After (Guardian):**
> Tweaks to event filter used in invul period guesses

- src/parser/core/modules/CastTime.js
- src/parser/core/modules/GlobalCooldown.js
- src/parser/core/modules/PrecastStatus.js
The recent GCD changes massively improved the accuracy of the durations, but didn't take into account casts that had been adjusted by spells like swiftcast.
This issue is most visible on RDM parses, as the high frequency of dualcast'd >2.5s casts was bloating the ABC calculation, and causing some funky shit in the timeline.
There's also a minor fix that forces `precastAction` to run before `precastStatus` so the events spliced by `precastStatus` are readable by the cast event for the action.
Using [this log](https://www.fflogs.com/reports/6KDf7GhvZNkq1AyR#fight=2&source=9) for the below.
**Before:**
**After:**
> Fix GCD length calcs when modified by castTime

- src/parser/jobs/nin/TrickAttackPositional.js
- src/parser/jobs/nin/index.js
- src/parser/jobs/nin/notes.md
Pretty much what it says on the box. It looks for TA casts and lines them up with vuln debuff applications from the player (in case there are 2+ NINs in the parse). I went with a 2-second window to be safe; most applications I saw in my logs while testing this out were in the 850-900ms range for how long it took from the cast to the debuff application, so I doubled it and rounded up.
> Added a module for missed Trick Attacks

- src/components/ui/TimeLineChart.js
- src/parser/jobs/rdm/Gauge.js
Currently no support for zoom/pan, the chartjs plugin that handles it is trash and my attempts at fixing it were dodgy at best.
Core UI module added to centralise the config for this sort of thing, should make it a bit easier to deal with / adjust them down the line.
PR also fixes RDM gauge to track deaths because hey graphs make this noticeable.
> RDM gauge graph

- src/parser/core/modules/AdditionalEvents.js
This adds an extra condition to `AdditionalEvents`' sort, to provide a defined order to events occuring at the same timestamp.
This should have a relatively minor effect across the board, and help make classes that rely heavily on buff procs much more reliable to write modules for. Examples are from a RDM log, as it's the job that is most heavily effected by the prior inconsistencies.
Open for feedback on the sort order, this should follow "expectation" but may need tweaks.
**Before:**
**After:**
> Event type sort order for events with same timestamp

- src/parser/jobs/nin/Ninki.js
- src/parser/jobs/nin/Weaving.js
Hellfrog was me being a dumb. For weaving, though, let me know if disagree with the change. I think it's the best way to handle it, since the only time you should _ever_ be double-weaving on NIN is if Huton is down and in that case you have bigger problems to worry about anyway.
> Fixed two minor bugs in the NIN modules

- src/parser/core/Parser.js
Mentioned it on Discord but I'll put it here for posterity - apparently `.toFixed(0)` is functionally equivalent to `Math.round()` plus a string conversion, which can result in the seconds displaying as 60 in `m:ss` format (something like 1:59.7 getting displayed as 1:60, for instance). I slapped on a small fix that explicitly floors it if precision is 0.
> Fixed a bug in timestamp display

- src/components/Find/FightList.js
- src/components/modules/Checklist.js
- src/components/modules/Suggestions.js
- src/parser/core/Module.js
- src/parser/core/Module.test.js
- src/store/actions.js
- src/store/reducers.js
- src/store/storage.js
Nothing particularly visible, just a few tweaks for end user QoL
* Made the "Kills Only" and "Show Minor" switches persist across navigation and reloads
* Capped checklist %s at 100 in production builds - dev server will still show >100 for debugging purposes
* Added helper function `module.removeHook`, not that people really need it
In looking around for a test case for the second - most of the ones that have been brought up recently have been fixed already, so great work to all involved w/ speedmod changes!
> QoL tweaks

- src/data/ACTIONS/PGL.js
- src/parser/jobs/mnk/BuffUptime.js
- src/parser/jobs/mnk/Fists.js
- src/parser/jobs/mnk/NOTES.md
- src/parser/jobs/mnk/Speedmod.js
- src/parser/jobs/mnk/index.js
Mostly building on @nfriendly's work in #110, I also added FoF uptime checking and fixed normalisation for speedmod a little. The checklist percentages here are very hit and miss and I'm on the fence about the severity but the logic is good so derp. If this is good to go, it also closes the older PR.
> MNK buff uptime tracking

- src/parser/core/Parser.js
- src/parser/jobs/smn/Pets.js
* Changes the implementation details of event fabrication. Fabricated events now occur _after_ the current main event has been parsed, instead of interrupting mid-way through the module execution.
* Tweaks handling in `smn/Pets` to prevent issues arising from the above change.
Assuming modules execute `A` -> `B`, and `event` in `A` triggers `fab`,
**Before:**
```
A event
A fab
B fab
B event
```
**After:**
```
A event
B event
A fab
B fab
```
> Implement fabrication queue via iterator

- src/parser/jobs/mch/Heat.js
Logs are weird. Sometimes the FT ticks come in _just_ shy of 1s apart, and we wind up with 5 ticks in 3953ms or something. Thusly, 50ms fuzz factor just in case. This shouldn't be a common occurrence (since it requires FT to be canceled with pretty much perfect timing) but it's one worth catching nonetheless.
> Added a fuzz factor to the Flamethrower tick calculation

- src/parser/jobs/nin/GlobalCooldown.js
- src/parser/jobs/nin/index.js
- src/parser/jobs/nin/notes.md
I added in a bit of special sauce for NIN so that TCJ wouldn't count against uptime. It basically just refunds you all the time you spent under TCJ, minus half a GCD's worth per cast (since you start it as a weave, not on the GCD). I also updated notes.md since it was a tad out of date.
> ABC improvements for NIN

- .editorconfig
- config-overrides.js
- package.json
- src/data/LANGUAGES.js
- yarn.lock
This PR adds %s to the locale menu that display how complete that translation is. %s are calculated at build time, so there's no loading of locale data to render the info.
Aiming for this to be the first part of a few updates to the i18n, hoping to get something _visible_ by 4.4!
Preview:
I have no idea how the lockfile ended up as CRLF but it is and I don't really want to deal with 9k+ line changes right now.
> Added completion% for languages in menu

- src/parser/core/modules/DoTs.js
- src/parser/jobs/nin/ShadowFang.js
Added a core module for tracking DoTs (and other should-always-be-up debuffs like Disembowel/Dragon Kick) so we can stop copy/pasting the SMN logic everywhere.
> Core DoTs module and a proof-of-concept Shadow Fang overhaul

- src/parser/jobs/whm/About.js
Asylum isn't currently tracked; Tick change has no effect here. No issues with this job module in 4.4
> WHM 4.4 Version update: 

- src/parser/core/modules/Death.js
Per issue #207, I twiddled the `Death.js` module so it ignores one death if the parse it's analyzing is a wipe, since bitching about the wipe-induced death is pretty unhelpful.
> Included a death refund for wipe logs

- src/parser/jobs/drg/Buffs.js
Turns out my B4B window suggestion was looking at the first _cast_, not the first GCD, so any windows that started with OGCDs were getting flagged as bad automatically.
> Fixed a bug in the B4B window suggestion

- src/parser/core/modules/Timeline/Timeline.js
- src/parser/core/modules/Timeline/Timeline.module.css
This PR:
- _Finally_ fixes gestures on touchpads.
- Scroll will now scroll the view (horizontally), ctrl+scroll will zoom. Click+drag works as before.
- Adds the new `timeline.show` function for other modules to consume.
@AkairyuGestalter this may be of interest to you - lmk thoughts on `.show` re: your stuff.
> Timeline tweaks

- src/parser/core/modules/HitType.js
- src/parser/core/modules/index.js
Basically Object boolean fields for `criticalHit` and `directHit`. Should be able to filter on these, for CDH would need both fields. Applies to `damage` and `heal` event types. AoE doesn't really support anything for individual hits that I know of so for finding AoE crits for example, would need to filter the damage events and the actual skill ID.
> Add Crit and Direct Hit tracking to events

- src/parser/jobs/nin/Weaving.js
Now it should fall back on the default logic for big weaves regardless of whether or not they included a Ninjutsu/duped DWaD cast, so the "ignore downtime weaves" logic should apply.
> Twiddled weaving logic for NIN

- src/parser/jobs/mnk/GreasedLightning.js
Final event for GL stacks and graph was missing due to a typo in the current stacks reference. TL;DR underscores.
> Fix a bug in GL event closing

- src/parser/jobs/mnk/GreasedLightning.js
Still not really happy with this logic, it basically calculates total GL3 spanning the whole fight even where downtime occurred. Maybe just using `getStatusUptime` with a filter on stacks could work, not sure how that goes for `applybuffstack` buffs. This should at least fix the log for Jojo Zep of Tonberry. Open to any ideas for subtracting downtime segments.
> Fix logs that ended on GL3 for uptime calculation

- src/parser/jobs/drg/BloodOfTheDragon.js
Because the `this._bloodDuration <= 0` check wasn't happening in the LotD reversion logic, the sim was falsely persisting BotD through lengthy downtimes and allowing the player to keep eyes they should've lost, offsetting their LotD windows and generally fucking everything up.
> Fixed a bug in the Blood of the Dragon simulation module

- src/components/Analyse/Analyse.js
- src/parser/core/Module.js
- src/parser/core/Parser.js
The use of the object and its keys made it more error-prone than just using an array to hold the modules.
`Promise.all` is guaranteed to return the results in the same order as the input iterable yielded them, regardless of load order, so we can trust the indexes to be the same.
> Totally unnecessary refactor of fetchEventsAndParse

- src/parser/jobs/drg/modules/Procs.js
Funny story, using one variable for the `value` and another in the `why` text for a suggestion produces goofy results.
> Fixed a minor DRG bug

- src/parser/jobs/mnk/modules/BuffUptime.js
- src/parser/jobs/mnk/modules/DISPLAY_ORDER.js
- src/parser/jobs/mnk/modules/Demolish.js
- src/parser/jobs/mnk/modules/GreasedLightning.js
This is basically a transparent change, Demo still needs work around GL0 and intentional clipping but the rules for it are complicated so just migrating to get rid of that annoying magic-numbers warning tbh.
> Move Demolish to core DoT module and add display order to MNK checklists

- src/data/ACTIONS/MNK.js
- src/parser/jobs/mnk/NOTES.md
- src/parser/jobs/mnk/modules/DISPLAY_ORDER.js
- src/parser/jobs/mnk/modules/GreasedLightning.js
- src/parser/jobs/mnk/modules/Undesirables.js
- src/parser/jobs/mnk/modules/index.js
This could probably be a core module tbh, seems relevant to NIN and BLM too.
Rolling in a minor bug fix to the suggestion on Earth's Reply to make the actual suggestion clearer. A more general rework of Earth's Reply needs to happen in the future since there are times it's worth having for defence that shouldn't penalise users. It's currently minor so won't show for most players which is why I'm leaving it for now.
> Add a check for undesirable MNK skills

- src/parser/jobs/mnk/index.js
Changes in 4.5 don't matter for analysis (they're for making mistakes less punishing), bumping version but no other changes required. We don't reference FoF potency so that's cool too.
> Bump MNK supported version to 4.5

- src/parser/jobs/mch/modules/Ammo.js
Turns out my logic for penalizing overwritten Ammo has been broken since pretty much the beginning of time. Yaaaaaay.
> Fixed a dumb Ammo bug

- src/components/App.js
- src/components/CombatantLookupRedirect.js
As per req. from Lethys, a redirect route that can redirect for data from the parses fflogs endpoint.
Redirects are based on players who participated in the specified fight, using both their name and job to distinguish. In the absolutely minuscule chance there's two players meeting that criteria, the first in the list will be picked. If the provided data is malformed, it'll try to fall back to the combatant listing page.
```
Format:
/lookup/:code/:fight/:job/:name
Example:
/lookup/vrX3A1mnR489zCkM/3/Summoner/A'kwell Dinhe
/analyse/vrX3A1mnR489zCkM/3/7/
/lookup/vrX3A1mnR489zCkM/3/Summoner/legit who
/find/vrX3A1mnR489zCkM/3/
```
> Combatant lookup redirect

- src/parser/jobs/drk/index.js
- src/parser/jobs/drk/modules/DarkArts.js
Reviewed DRK module to confirm that there is no handling for tick count recommendations for Salted Earth (effected by the 4.4 patch).  No other class changes from 4.4 or later patches.
While reviewing module, determined that there was incorrect simulation & recommendations for Dark Arts regarding the enmity combo - module was incorrectly crediting Spinning Slash as a DA consumer, and making a recommendation to use DA for both Spinning and Power Slash equally.  Removed tracking variables that were made obsolete by fixing the incorrect simulation of DA+Spinning Slash.
> Update DRK for 4.5, fix bug with DA + enmity combo recommendations

- src/parser/jobs/drk/index.js
- src/parser/jobs/drk/modules/Buffs.js
- src/parser/jobs/drk/modules/GCDs.js
- src/parser/jobs/drk/modules/OGCDDowntime.js
- src/parser/jobs/drk/modules/ResourceSimulator.js
- src/parser/jobs/drk/modules/index.js
Remove normalized uptime calculations for Blood Weapon/Delirium, track as oGCDs instead
Add TieredSuggestion for using Delirium without extending BW/BP
Convert dropped GCD suggestion to TieredSuggestion, fix bug of not actually calling onComplete to add suggestion
Clean up magic constant values in resource simulator
> DRK linter cleanup, improved oGCD tracking and bug fixes

- src/parser/jobs/drk/modules/ResourceSimulator.js
Fix incorrect mana generation for Carve & Spit - only count when DA is not active
Fix incorrect blood generation for Salted Earth - look for status damage ID, rather than action ID
> DRK resource simulator bugfixes

- src/parser/jobs/drk/modules/Buffs.js
- src/parser/jobs/drk/modules/OGCDDowntime.js
- src/parser/jobs/drk/modules/ResourceSimulator.js
- Fix omission of Carve & Spit from tracked oGCDs
- Bug fix (workaround) for logs with two Darkside applybuff events without a removebuff in between.  Assume Darkside is on continuously from the first applybuff event (ignore the "duplicate" event)
- Add Blood gauge graph per #353
> DRK updates

- src/data/PATCHES.ts
It seems patch 4.05 is merged to 4.06 so the update times are same
> backfill update times of CN edition

- src/components/ui/TimeLineChart.js
Before:
After:
`tooltipFormat` is the property used by Chart.js for displaying the hover tooltip. Documentation [here](https://www.chartjs.org/docs/latest/axes/cartesian/time.html#configuration-options).
This is kind of a hacky way to fix it, but it works. Basically, it assumes that the input timestamp is an offset from 0ms, and we treat that like a UNIX timestamp. Conveniently, it thus displays as a "relative" timestamp from wherever we started.
Full list of uses:
```
➜  xivanalysis git:(TimestampFix) ✗ grep -r 'TimeLineChart' src
src/components/ui/TimeLineChart.js:export default class TimeLineChart extends PureComponent {
src/parser/jobs/drk/modules/ResourceSimulator.js:import TimeLineChart from 'components/ui/TimeLineChart'
src/parser/jobs/drk/modules/ResourceSimulator.js: …
```
> Update tooltip format for timeline charts to display relative timestamps

- src/data/ACTIONS/BLM.js
- src/parser/jobs/blm/modules/Gauge.js
- src/parser/jobs/blm/modules/RotationWatchdog.js
- Update new BLM actions with IDs and icons, remove TODO-style comments
- Update Gauge; Despair does not consume Umbral Hearts
- Update expected fire 4 after Manafont from 2 to 1
- Despair -> Manafont -> Fire 4 -> Despair is now preferred
> BLM ShB Action ID and Rotation Tweaks 

- locale/en/messages.json
- src/parser/jobs/war/modules/InnerRelease.tsx
Make missedGaugeDumps (incorrect GCD in IR window) more descriptive, clarify when Decimate is better than Fell Cleave
> Warrior IR copy cleanup

- src/data/ACTIONS/LNC.js
- src/data/STATUSES/DRG.js
- src/parser/core/modules/Combos.tsx
- src/parser/jobs/drg/index.js
Apparently we had the wrong status ID loaded for Disembowel. I feex.
> Updated Combos module for DRG plus a small bugfix

- src/parser/jobs/gnb/index.tsx
Forgot to do this in the bugfixing pass. I'm comfortable with marking this class as officially supported. There are a few improvements that I want to make to it, but it's functional enough.
> Mark GNB as supported for 5.0

- src/parser/jobs/gnb/index.tsx
No actual job changes from patch notes.
> Mark GNB as supported for 5.01.

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/data/STATUSES/DRG.js
- src/parser/jobs/drg/modules/Buffs.js
Apparently the Right Eye status has a different ID if you don't have a tether buddy, so analysis was going goofy on dummy logs or any time someone's macro fizzled (or they were just being dumb). This should fix it, plus add a minor suggestion to make sure you always tether someone in group content if it detects the solo Right Eye status.
> Dragon Sight bugfix

- src/parser/jobs/pld/index.tsx
- src/parser/jobs/pld/modules/Weaving.tsx
- src/parser/jobs/pld/modules/index.tsx
Title.
Sample log with double weaves under Requiescat: https://www.fflogs.com/reports/rF8NmGvLgxzp9JqA#fight=9&type=damage-done&view=events&source=5&sourcebuffs=-1000076&ability=16459
```
00:04:02.721 | Damelia Lhea Holy Spirit Innocence *18266*
00:04:03.456 | Damelia Lhea Spirits Within Innocence 8418
00:04:04.183 | Damelia Lhea Intervene Innocence 4654
00:04:05.216 | Damelia Lhea Holy Spirit Innocence 15661
```
> Override Weaving for PLD to support instant-cast spells under Requiescat.

- src/parser/jobs/mch/modules/YassQueen.js
Turns out that trying to do `array[array.length - 1]` when `array.length` is 0 and then hitting references on the result makes things explode slightly. Who knew?
> Fixed an empty Queen window crash

- src/parser/jobs/pld/index.tsx
- src/parser/jobs/pld/modules/Weaving.tsx
It's fine to defer this to core Weaving module anyways because it's impossible to have the Requiescat buff at the start of any sensible log -- you need a target to cast it.
Sample log: https://www.fflogs.com/reports/JKFPG7n9tB3MNmrR#fight=6&source=27&type=casts&view=events
Bad sequence:
Fixed weaving window:
> Check for numpty PLDs opening on weaved oGCDs.

- src/parser/jobs/rdm/index.js
- src/parser/jobs/rdm/modules/Gauge.js
Fixed Enchanted Moulinet to cost 20 White|Black instead of the old 30.  Also added a retroactive (for 5.0) Change Log specifically so I don't forget when I mark it fully supported.
> BugFix - RDM Enchanted Moulinet Cost

- src/parser/jobs/ast/modules/Sect/Sect.tsx
It's not fair to give a suggestion to switch stance on if they simply didn't use any stance spells.
> AST BUGFIX: Sect detection fails should not generate suggestion

- src/parser/jobs/drg/modules/Weaving.js
Smol bugfix. Double-weaving on Stardiver is a no-no.
> [Bugfix] Added Stardiver to the list of bad weave jumps

- src/parser/core/modules/AoE.js
- src/parser/jobs/drk/modules/ResourceSimulator.js
- src/parser/jobs/rdm/modules/Gauge.js
Aggregation was merging the entire hit object, rather than just the successfulHit property.  
This also supersedes the change to Gauge.js in #497, per my discussion with Cephid in the dev channel.  This PR should win on the merge conflict for that specific file.
> fix: aggregate the successfulHit property correctly

- src/parser/jobs/brd/changelog.js
Somehow, this slipped my testing, but without this, the entire module breaks.  oops.
> Add Contributors array to Change Log

- src/parser/jobs/brd/modules/PitchPerfect.js
Otherwise it will send an error the the sentry and that's annoying.
> Added a check to see if they even cast PP once

- src/data/STATUSES/SCH.js
- src/parser/jobs/sch/modules/Aetherflow.js
This addresses a bug with recitation messing with aetherflow counts. The code obviously isn't perfect, but the extra structure should open the door to monitoring recitation uses in future updates.
Fixes #489
> Fix aetherflow counts

- src/parser/jobs/sch/modules/Aetherflow.js
This should not affect the majority use case of xivanalysis for SCH (instanced raids, etc), but it could look bad if it's content like dungeons or when they have a parse where they started with aetherflow stacks.
For some examples of where this currently breaks, see the following:
* [striking dummy test](https://xivanalysis.com/analyse/M6bkczhpNrAR2Pqd/3/7/)
* [old content where AF could be used outside of combat](https://xivanalysis.com/analyse/nV4z6WXbqjy9vHd1/219/5888/)
Won't help with old content, but I'd rather cover the edge case for current content anyway.
> Fix issue with single stack use

- src/parser/core/modules/Combos.tsx
Currently, combos don't get marked as broken if they are restarted with a new combo starter.  This can lead to some unexpected behavior, as seen here: https://xivanalysis.com/analyse/pkGqAXfKBdC1gQMH/1/1/ -- only 1 "broken" combo is recorded for all the Hard Slash / Syphon Slash alternations, and only when he does Hard Slash > Souleater
Fix changes the logic to detect all of those Hard Slashes as separate combo breaks, will display as:
> Fix combos so they break on restarting a combo

- src/data/ACTIONS/ACN.js
- src/data/ACTIONS/SCH.js
- src/parser/jobs/sch/modules/Weaving.js
- src/parser/jobs/smn/modules/Ruin2.js
SCH has a separate Ruin II ability from ACN with its own id. This commit simply adds that ability to the SCH job actions.
Compare:
ACN: https://garlandtools.org/db/#action/172
SCH: https://garlandtools.org/db/#action/17870
> Add Ruin II to SCH

- src/parser/jobs/gnb/index.tsx
As there were no battle system changes to GNB in 5.05, I believe this is safe to bump.
Probably wasn't bumped since no-one was watching this? Working as intended!
> 5.05 GNB - Version bump

- src/parser/core/modules/Combos.tsx
- src/parser/jobs/dnc/changelog.tsx
- src/parser/jobs/dnc/modules/Combos.ts
- src/parser/jobs/dnc/modules/DirtyDancing.tsx
- src/parser/jobs/dnc/modules/index.ts
Core Combos updated to include overrideable function that allows subclasses to flag broken combos as allowable.
DNC combos module to select an appropriate icon, and allow Flourish to drop if both Standard and Technical Steps are used during Cascade's combo window.
Note that this will be affected by #514 since it's currently referencing the AoeEvent from Core Combos.
> Core+DNC allowable dropped combos

- src/parser/jobs/dnc/modules/DirtyDancing.tsx
Step drift refund didn't account for unabletoact time, switching from getInvunlerableUptime to getDowntime since that does. E1S is fun...
> [BugFix] Fixing step drift calculation downtime refund

- locale/en/messages.json
- src/parser/jobs/ast/index.tsx
- src/parser/jobs/ast/modules/Horoscope.tsx
It just wasn't working. Original intent was to track the entire cycle:
1. Used horoscope, track the 10s buff
2. Did they use a helios cast to upgrade it?
3. Track the upgraded 30s buff
4. Spit out warning if either buff expired.
Unfortunately, `removebuff` comes before activation in the logs whether or not they activated in time. 
For now, we're just going to go with this very sad implementation that works accurately for the suggestion we're trying to make.
> [BUGFIX] AST Horoscope reworked for accuracy (._.)

- src/parser/core/modules/BuffWindow.tsx
- src/parser/jobs/drk/modules/Delirium.tsx
- src/parser/jobs/war/modules/InnerRelease.tsx
Per comment at the conclusion of #517, cleaning up the iconAction to change to expect an icon URL string, since that's all we're using that property for.
> clean: change iconAction to expect icon URL

- src/data/ACTIONS/SCH.js
The existing actions for the player's casts of Whispering Dawn and
Fey Illumination were using the fairy's ability ids.
- Move existing listings for Whispering Dawn and Fey Illumination to
the fairy's actions, distinguished with the `pet` flag set to
`true`.
- Create listings for the player's action for Whispering Dawn and Fey
Illumination.
Signed-off-by: Panic Stevenson <Panic.Stevenson@gmail.com>
> Fix Scholar Pet Action IDs

- src/data/ACTIONS/SCH.js
Update Scholar actions to match values listed in the 5.05 job guide.
- Remove erroneous cast times from Biolysis and Art of War.
- Update Succor's cast time to 2s to reflect 5.05 job changes.
- Update fairy summon actions to be on the GCD with a 2.5s cast time.
- Remove fairy action cooldowns.
Signed-off-by: Panic Stevenson <Panic.Stevenson@gmail.com>
> Update Scholar Actions to Match 5.05 Job Guide

- src/data/ACTIONS/MRD.js
- src/data/ACTIONS/WAR.js
- src/data/STATUSES/WAR.js
Update Warrior actions to match values listed in the 5.05 job guide.
- Remove Unchained.
- Add Shake It Off and Holmgang to Warrior statuses.
- Add and update Warrior status durations.
- Add and update Warrior action potencies.
- Update Marauder and Warrior action cooldowns.
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>
> Update Warrior Actions to Match 5.05 Job Guide

- locale/en/messages.json
- src/parser/jobs/mch/modules/Heat.js
- src/parser/jobs/mch/modules/Reassemble.js
Fixed a bug (that no one ever noticed because dropping Reassemble is rare) and updated the wording on the Overheat section of the page per discussion yesterday in #dev-ranged. I figured I'd just lump that in here so I don't forget.
> Small bugfix and wording update for MCH

- src/parser/core/Module.ts
Fixes issue with an "unknown node" error when navigating to a different report/class after viewing a report for a class that extended a core module to add a class specific dependency (e.g. DNC Combos, MNK Speedmod)
> Clone parent dependency array into child classes

- src/parser/core/modules/Gauge/CounterGauge.ts
Greased Lightning gauge needs to know the current value. Might be worth having a getter on the max too but I don't think any other jobs need that, and I can work around it with the constants I use to set it in the first place.
> Add a getter for the CounterGauge current value

- README.md
Update the main README.md documentation to have the current Final Fantasy XIV expansion title.
> Update Final Fantasy XIV Expansion Title

- src/parser/jobs/pld/index.tsx
- src/parser/jobs/pld/modules/Requiescat.tsx
Verified this with one of my own Titan logs: https://www.fflogs.com/reports/cJmALtK2zX1CZwjf#fight=13&type=damage-done
Live: https://xivanalysis.com/analyse/cJmALtK2zX1CZwjf/13/7/
This is important to start checking because the duration of the downtime in Titan means that it is potency-positive to slam that mf Requiescat button before he transitions from small to big. You only get a Confiteor out of it, but the next Req comes up on time anyways.
This should theoretically also work for Maelstrom in Leviathan, but the potency-positive solution there is a FoF window, not a Req window. I'll update that one later, since it'll require a rewrite of how FoF is analyzed.
> Don't penalize for rushed Requiescat windows.

- src/components/ui/RotationTable.tsx
- src/parser/core/modules/BuffWindow.tsx
Keeps the current default, but accepts an optional property to specify what the "Rotation" section title should be.  This PR also extends BuffWindowModule to expose override property for RotationTable header
> Extend RotationTable to allow overriding the headerTitle

- src/parser/jobs/drg/modules/Debuffs.js
Chaos Thrust's DoT is 24s duration, so it's impossible to keep it up 100% of the time. It actually drops a lot naturally as the rotation lines up.
90% is what we use for Goring Blade on PLD, so I figure this is a good enough baseline to catch most cases.
> Set baseline CT uptime to 90%.

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/parser/jobs/smn/modules/DWT.js
Removed 6 GCD suggestion that is no longer accurate.
Fixed a bug that caused DWTs without a Deathflare to not end properly since DWT no longer has a buff component in fflogs.
> Further corrections to DWT suggestions.

- src/parser/core/modules/AoE.js
- src/parser/core/modules/Entities.js
- src/parser/core/modules/HitType.js
This fixes:
- SAM events showing broken combo for the last GCD used under Meikyo Shisui: https://xivanalysis.com/analyse/1W3bkrcGFBtNKvHn/1/8/
After:
- DRG (and probably other classes) showing incorrectly broken combos when overkilling the target: https://xivanalysis.com/analyse/zVd9Zt4ynKXa7jYQ/1/1/
After:
- DRK MP graph not showing correct MP values: https://xivanalysis.com/analyse/AG1wtcnXWLVKZmkv/2/6/
After:
> [Fix]: Move core Entities and AOE to calculateddamage events for compatibility

- src/parser/core/modules/AoE.js
- src/parser/core/modules/Entities.js
- src/parser/core/modules/FFLogsEventNormaliser.ts
- src/parser/core/modules/index.js
Hook both calculated damage/heal events and "base" damage/heal events.  If we see a calculated event (which occurs at same timestamp as corresponding cast event and will always be before the damage/heal event), stop listening for base events, since this is a new log.
> Backwards compatibility for FFLogs calculated events change

- src/parser/core/modules/GlobalCooldown.js
Time between GCD starts is used for estimation, so excluding instant casts we need the larger of gcd recast and cast time to normalise with.
Currently sub-gcd casts are overestimated by a factor of 2.5/cast time
> Fix normalisation constant for sub-gcd casts

- src/data/ACTIONS/MCH.js
- src/parser/jobs/mch/modules/Gauge.js
Small update so old synced content doesn't display logs as broken. This is only a resource sim/combo action update. I'm not bothering to add analysis for Rook Autoturret usage; the Automaton Queen section of the parse will still come up empty even though Battery expenditure is calculated properly.
> Added old actions to the sim and combo validity for unheated shots

- src/parser/core/Parser.tsx
- src/parser/core/modules/BrokenLog.tsx
As per request. Keep ya fingers on the revert buzzer for this one, I've got no insight on how often these fire, and we might flood sentry.
> Capture broken log triggers on sentry

- src/parser/jobs/smn/modules/Weaving.ts
Original implementation allowed any triple weave that included a FBT.  Now only a triple weave after an instant GCD with FBT as the second weave is allowed.  The following will now be considered bad weaves:
* 3 weaves, Phoenix 3rd, after R2/4
* 3 weaves, Phoenix 2nd, after hardcast R3
* 3 weaves, Phoenix 1st, after R2/4
> Improved Firebird Trance triple-weave check

- src/parser/jobs/smn/modules/Ruin2.js
Addresses the sentry for https://xivanalysis.com/analyse/6XzmWcFPZfGqYCtw/9/1/
> Fixed a check that could error if no OGCDs had been used before Ruin4

- src/parser/jobs/smn/modules/Demis.js
If the expected number of usages is reached, the number will now be green (uses text-succes style).  Anything less will keep the default text color.
> Now color demi skill usage counts

- src/parser/jobs/brd/modules/Sidewinder.js
Fixing issue with Shadowbite hit detection. Was using the dmg timestamp which is going to be little different for each enemy hit. 
Fix I implemented was just use the last cast timestamp instead of the dmg event timestamp. I tried to write a test but ended up with quite a bit of set up for the events.
Example of log with issue
https://xivanalysis.com/analyse/BdkGL9728rXnWFgN/1/13/
> fix: Use cast time when tracking shadowbite dmg

- src/parser/jobs/smn/index.js
No known remaining inaccuracies/misinformation, so marking supported.
> Marked SMN as supported.

- src/api.ts
- src/fflogs.ts
Title. Wasn't going to handle this, but it's been happening more often than I can afford to ignore.
Basically just bypassing the cache on the second try to make sure we've not cached the blank trash, falling back on a better error message.
> Add rudimentary handling for malformed event responses

- src/data/PATCHES.ts
Date for CN 4.5 was May 28, according to this?
http://ff.sdo.com/web8/index.html#/newstab/newscont/306488
> add CN patch date 4.5 and shb

- src/parser/core/modules/FFLogsEventNormaliser.ts
Title, as per braindump last night. I checked existing usages - with the steppies change, this shouldn't hit any _existing_ code. Hopefully it makes the issue waaaaayyyy more obvious to other devs.
> Throw error if accessing normalised data before normalisation

- src/parser/core/Dispatcher.test.ts
- src/parser/core/Dispatcher.ts
- src/parser/core/Module.test.js
- src/parser/core/Module.ts
- src/parser/core/Parser.test.js
- src/parser/core/Parser.tsx
- src/parser/core/modules/Gauge/TimerGauge.ts
- src/parser/jobs/smn/modules/Pets.js
Or at least _less_ wibbly wobbly timey wimey.
Moved hooking logic out of `Module` into a new single-ish-ton `Dispatcher`. Filter QoL remains in modules to keep the dispatcher simple(r).
> Make time linear again

- locale/en/messages.json
- src/parser/jobs/blm/index.js
- src/parser/jobs/blm/modules/Gauge.js
- src/parser/jobs/blm/modules/RotationWatchdog.tsx
- Allow the Astral Fire cycle optimization where, with enough speed (Triple and/or Leylines generally required), the player can skip Blizzard 4 and Fire 1, and just do 5 Fire 4s and a Despair as their Astral Fire phase
- Stop dinging Enochian drops where it occurred during an UnableToAct window longer than the duration of the Astral Fire/Umbral Ice buff. I'm looking at you E1S.
> BLM - Cycle optimization & downtime enhancements

- src/parser/jobs/smn/index.js
- src/parser/jobs/smn/modules/Pets.js
Title. Should fix logs where the same demi window was being counted twice, with the first "window" only containing a single hit, if any.
> Add pet resync buffer to prevent late-resolution desyncs

- src/data/ACTIONS/SCH.js
- src/parser/jobs/sch/index.js
- src/parser/jobs/sch/modules/FaerieGauge.js
My death has been greatly exaggerated.
* Change the faerie gauge warning to start at 50 overcap (and only a minor warning only) per balance request and discussion
* Change consolation cooldown time to match with patch update
* Since I touched a module, I went ahead and updated `addHook` to `addEventHook` in there.
Happy 5.1 everyone!
> SCH 5.1 support and a minor nit from balance fix

- src/parser/jobs/war/TODO.md
- src/parser/jobs/war/index.js
This PR marks WAR as supported for 5.0-5.08 and updates the TODO list for WAR.
I haven't been able to dig up any bugs in the WAR modules that aren't core and equally present in other jobs that are marked as supported, and so it seems like there's no current reason to not mark WAR as supported. Some features (listed in the new TODO) would be nice to have, but again shouldn't be blocking of support.
> Mark WAR as supported through 5.08 

- src/parser/jobs/dnc/changelog.tsx
- src/parser/jobs/dnc/modules/Technicalities.tsx
Fixing a bug where simultaneous buff removal events for Devilment and Technical Finish would leave the window open inappropriately
> Ensure Technical Finish windows close correctly

- package.json
- src/components/Analyse/Analyse.js
- src/components/CombatantLookupRedirect.js
- src/components/GlobalSidebar/GlobalSidebar.js
- src/components/I18nLoader.js
- src/components/I18nOverlay.js
- src/parser/core/modules/AdditionalEvents.js
- src/parser/core/modules/CastTime.js
- src/parser/core/modules/Checklist/Component.js
- src/parser/core/modules/Checklist/Rule.js
- src/parser/core/modules/CooldownDowntime.js
- src/parser/core/modules/Cooldowns.js
- src/parser/core/modules/Entities.js
- src/parser/core/modules/GlobalCooldown.js
- src/parser/core/modules/Invulnerability.js
- src/parser/core/modules/Suggestions/Component.js
- src/parser/core/modules/Weaving.js
- src/parser/jobs/blm/modules/Weaving.js
- src/parser/jobs/sam/modules/Tsubame.js
- src/parser/jobs/sch/modules/Aetherflow.js
- src/parser/jobs/sch/modules/Interrupts.js
- src/parser/jobs/smn/modules/Ruin2.js
- yarn.lock
This PR updates, like, everything. Except the stuff it doesn't.
Highlights:
- [TypeScript 3.7](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/)
- eslint updates (hence the code changes)
- no chart.js update because it totally broke colours and i couldn't be bothered debugging why it wasn't working
>  Update dependencies

- .neutrinorc.js
- package.json
- yarn.lock
title
due to the quantity of not-ts in the codebase, ts is configured to do minimal work, babel does the rest.
adding plugins for `??` and `?.`
> Add babel plugins for recent TS features

- src/parser/jobs/drg/modules/BloodOfTheDragon.js
Fix for CLIENT-18T; the BotD module was trying to call `timeline.show()` without having `timeline` as a dependency.
> [Bugfix] Fixed a small sentry error in BotD

- src/parser/core/Module.ts
Inspired by #713
Color is derived from the module handle. I've _tried_ to make it readable on both light and dark themes. No promises for yellow though - try renaming your module? :^)
I slep now
> Add module debug logging fn

- src/parser/core/modules/Combos.tsx
Small fix for the issue that presents here: https://xivanalysis.com/analyse/3X9TbDyqKMLkf6G2/25/2/
Basically what's happening is that non-combo-breaking-but-not-combo-continuing GCDs (e.g. Shadow Fang, Drill, Air Anchor, and in this case, Flamethrower) are artificially extending the simulated combo timer, which can lead to erroneous broken combo warnings after downtime. In the log linked above, a FT during downtime resets the timer so it yells about a broken combo despite the fact that it had already fallen off during the transition.
> [Bugfix] Fixed improper combo break warnings

- src/data/STATUSES/root/RDM.ts
- src/data/STATUSES/type.ts
- src/parser/core/modules/PrecastStatus.js
Most noticeable for Acceleration (RDM) - when this was changed to a 3 stack buff in 5.1, we are now getting an `applybuff` event and an `applybuffstack` event with 2 stacks on the RDM's first cast of the pull.
See, for example: https://www.fflogs.com/reports/mphJdArR6vbTHLKj#fight=2&type=auras&source=1&view=events
This fix is just for RDM, but should be extensible to other similar jobs fairly easily.
> [Bugfix] Fix precast status for buffs that apply stacks

- src/parser/jobs/drk/modules/OGCDDowntime.ts
Per discussion with Demon on the Balance discord, in light of the changes made to the CDDT module.  It was noted that initial usage timing and order of Plunge, C&S, Salted Earth, and Abyssal Drain can vary by comp, with a "worst case" of 12th-13th GCD.  For initial tuning, I'm setting this 8th GCD and will adjust further if necessary.
> Update DRK CDDT

- src/parser/jobs/drg/modules/Positionals.js
* add 200ms buffer for true north cd to allow for really fast uses
* fixed issue where additional hook would be added while a charge was already running it's cd
> DRG: Bugfix for true north charge counter and cd buffer

- src/data/ACTIONS/root/NIN.ts
- src/parser/jobs/nin/modules/TrickAttackUsage.js
Yeah so apparently there are two versions of Ten that actually get used but not of Chi or Jin? Neat, I guess. Except it really isn't. But whatevs. This should fix the timeline so it actually shows the Ten cast on Hyosho now.
> [Bugfix] Added second ACTIONS entry for Ten because SE things

- src/parser/jobs/drg/modules/Positionals.js
Discovered this bit of a logic error while looking at a log for (somewhat fittingly) `Missed Positional`. Bug can be seen in this log on live: https://www.fflogs.com/reports/xHWN8mXpMjPr6k3G#fight=1&type=damage-done
Added a check to make sure the RT proc attempt doesn't get counted if the second combo doesn't land. If it was dropped due to a broken combo, the `Procs` module should show a suggestion for that, and this module won't count it (as it's not even relevant if you drop the FC/WT proc).
Also cleaned up some unused code.
> Bugfix: DRG reported RT procs as possible during invuln

- src/parser/jobs/drg/modules/OGCDDowntime.ts
Tightening up the first use offset based on latest use times in both DRG openers (low/high skill speed).
> DRG: Adjust first use offset for CDDT

- src/parser/jobs/drg/modules/BloodOfTheDragon.js
Super tiny bugfix: dragon sight used without a partner will now appear in the buff list for life of the dragon windows.
> bugfix: track solo dragon sight in lotd window

- src/parser/jobs/drg/modules/Positionals.js
Table was displaying "raiden thrust" as the missed positional. Fixed to show which of FC/WT was the missed proc action.
> Bugfix: DRG - display proper action in missed positional table

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/parser/jobs/dnc/changelog.tsx
- src/parser/jobs/dnc/modules/Technicalities.tsx
- Count the number of players affected by your technical finish buffs
- Show the number of players affected in the rotation table display
- If the player did not contribute to this window's buff (ie, another dancer initiated the window, and this dancer's buff didn't overwrite theirs at all), this will display as a 'N/A'
> DNC - Count/Show Players Buffed by Tech Finish

- src/parser/core/modules/DoTs.js
- src/parser/core/modules/Entities.js
- src/parser/core/modules/EntityStatuses.ts
- src/parser/core/modules/index.js
- src/parser/jobs/blm/modules/RotationWatchdog.tsx
- src/parser/jobs/brd/modules/Util.js
- src/parser/jobs/dnc/modules/DirtyDancing.tsx
- src/parser/jobs/drg/modules/Buffs.js
- src/parser/jobs/mnk/modules/Fists.tsx
- src/parser/jobs/mnk/modules/TwinSnakes.tsx
- src/parser/jobs/sam/modules/Buffs.js
- src/parser/jobs/sam/modules/Higanbana.js
- src/parser/jobs/smn/modules/DoTs.js
- src/parser/jobs/war/modules/StormsEye.js
- src/parser/jobs/whm/modules/DoTs.js
This is in support of #670 and the effort to switch to targetability events for invulnerability.  This should break the dependency from entities to invulnerability, and resolve the circular dependency created from switching to targetability events.  
I only lifted out the getStatusUptime method (and duplicated some of the buff tracking) because the existing Entities module is populating entity.buffs for each processed entity, which some modules depend on via entity.hasStatus (Bard Barrage tracking, for one).
I've reviewed a few jobs and confirmed that calculated DoT uptime is exactly the same for most of them.  White Mage DoT tracking on Titan is coming up with (very slightly higher) different numbers, though on fights like Leviathan it's exactly the same, so there seems to be some …
> Refactor entities.getStatusUptime() into separate module

- src/parser/jobs/blu/changelog.tsx
- src/parser/jobs/blu/modules/Weaving.ts
- src/parser/jobs/blu/modules/index.tsx
- Reduce false positives by greenlighting speedy and effective use of Surpanaka
- Surpanakha is best used 4 times between GCDs, with no other actions
weaved in, in a maximum of 5 seconds between GCDs
> Add BLU Weaving module

- src/parser/jobs/smn/modules/GeneralCDDowntime.ts
Most important part here is getting rid of the 4s fuzz time leftover from the previous implementation.  First use offsets also added to improve accuracy.
> Adjusted allowedDowntime and firstUseOffset for SMN cooldowns.

- src/parser/core/Parser.tsx
- src/parser/core/modules/AoEUsages.tsx
- src/parser/core/modules/Combos.tsx
- src/parser/core/modules/NormalisedEvents.ts
- src/parser/jobs/dnc/modules/Combos.ts
- src/parser/jobs/dnc/modules/DirtyDancing.tsx
- src/parser/jobs/dnc/modules/Esprit.tsx
- src/parser/jobs/dnc/modules/FeatherGauge.tsx
- src/parser/jobs/dnc/modules/Technicalities.tsx
- src/parser/jobs/drk/modules/Darkside.js
- src/parser/jobs/drk/modules/ResourceSimulator.js
- src/parser/jobs/gnb/NOTES.md
- src/parser/jobs/gnb/modules/Ammo.tsx
- src/parser/jobs/mnk/modules/MnkAoE.tsx
- src/parser/jobs/nin/modules/Ninjutsu.js
- src/parser/jobs/nin/modules/Ninki.js
- src/parser/jobs/rdm/modules/Gauge.js
- src/parser/jobs/sam/modules/AoeChecker.js
- src/parser/jobs/sam/modules/Combos.ts
- src/parser/jobs/smn/modules/DWT.js
- src/parser/jobs/smn/modules/Pets.js
(damage and applybuff were the only two being consumed)
This isn't ready for merge yet, as I haven't been able to test it, since FFLogs is melted this evening, but I wanted to go ahead and post the code changes for review/comment.
Jobs/Modules to test:
> Deprecate aoeX and migrate consumers to normalisedX

- src/parser/core/EventSorting.ts
- src/parser/core/modules/AdditionalEvents.js
- src/parser/core/modules/NormalisedEvents.ts
Per discovery today that the gauges break in fun and exciting ways if they don't get events in timestamp order, and that there isn't anything running after all the normalisers to re-sort the events array.
I refactored this out of AdditionalEvents and both AdditionalEvents and NormalisedEvents are now referencing the same sort logic.  The BLM Gauge normaliser is still doing its own sorting of sorts (tracking insertAfter for events it needs to generate and then splicing in at the appropriate point at the end), but on quick scan I'm not seeing other normalisers that are doing sort-like things with their synthetic events (aside from AOE, which is going to be removed after the NormalisedEvents migration is finished).
> fix: Sort normalisedX events into the event array to maintain expected ordering

- src/parser/jobs/drg/index.js
> Mark DRG as supported for 5.2

- src/parser/jobs/whm/index.js
Since no analysis-based breaking changes were made, this should be fine.
> Update support for WHM to 5.2

- src/parser/core/modules/AoEUsages.tsx
- src/parser/core/modules/Combos.tsx
- src/parser/core/modules/NormalisedEvents.ts
- src/parser/jobs/brd/modules/Sidewinder.js
- src/parser/jobs/dnc/modules/DirtyDancing.tsx
- src/parser/jobs/dnc/modules/Esprit.tsx
- src/parser/jobs/dnc/modules/FeatherGauge.tsx
- src/parser/jobs/drk/modules/ResourceSimulator.js
- src/parser/jobs/gnb/modules/Ammo.tsx
- src/parser/jobs/mnk/modules/Steppies.tsx
- src/parser/jobs/nin/modules/Ninjutsu.js
- src/parser/jobs/nin/modules/Ninki.js
- src/parser/jobs/rdm/modules/Gauge.js
- src/parser/jobs/sam/modules/AoeChecker.js
- src/parser/jobs/smn/modules/DWT.js
- src/parser/jobs/smn/modules/Pets.js
In light of e6s confirming that "ghosted" hits still advance combo and generate gauge, this is to adjust the semantics of normalised events (and combo events) to behave the same way as the in game combos & gauge generation do.
Renamed & adjusted the getters on the NormalisedEvent base class per semantics discussion in Discord, fixed downstream consumers as required.
> [BugFix] Adjust Successful Hit semantics and logic for ghosted hits

- src/parser/core/modules/CooldownDowntime.tsx
- src/parser/jobs/dnc/modules/OGCDDowntime.tsx
This aims to reduce the number of 14/12 type situations.
Jobs wanting to mark skills for pre-fight usage consideration should change firstUseOffset to a negative number.  Charged skills are not supported for pre-fight usages at this time.
Downtime usages are handled for all skills.  (In one of the logs that prompted this change, Energy Drain was used on True Heart, which did no damage, but gave Aetherflow, so I did not limit downtime usage checking to only cooldowns with pre-fight usage checking.)
> Modified core CDDT to handle pre-fight and downtime usages.

- src/data/STATUSES/layers/index.ts
- src/data/STATUSES/layers/patch5.1.ts
- src/data/STATUSES/root/WAR.ts
- src/parser/jobs/war/index.js
No changes to the job since 5.08 anyway, I won't take over as maintainer as such but I'll keep an eye on the module and handle any bugs, maybe tackle some of the TODO.
I didn't add layers for the status changes, mostly because they're not used at all in analysis.
> Bump WAR to support 5.2

- src/parser/core/modules/EntityStatuses.ts
Under certain circumstances (most notably e6s), if a DoT is continuously maintained but the boss goes invulnerable in the middle of the duration, the process to exclude the invuln time (and thus not double-count it) from DoT uptime isn't properly synthesizing the "second half" of the DoT duration, due to checking the wrong object.
> [BugFix] Low DoT uptime calculation when boss is invuln mid-DoT

- src/parser/core/modules/EntityStatuses.ts
If a DOT overran the end of the fight (seems to be mostly prevalent in wipe logs), there's no stack history event for the removal of the DOT, which broke an assumption of the process that split a status range due to invulnerability.  Given that this was a simple fix (if somewhat requiring an inelegant comment), I'm too lazy to go looking through consumers to figure out if we even need to care about the stack history :blobknife:
> [BugFix]: Undefined reference error when synthesizing new stack history

- src/parser/core/modules/BuffWindow.tsx
- src/parser/core/modules/Swiftcast.tsx
* Provide our own `reduceExpectedGCDsEndOfFight` method that totally doesn't just rip off the original at all
* Redefine `expectedGCDs` in init (lemme know if you want me to move this to the constructor instead) so that inheriting classes can provide their own suggestion content and severity tiers.
> Bugfix negative expected GCDs in Swiftcast module

- src/data/ACTIONS/root/NIN.ts
- src/parser/jobs/nin/modules/Ninjutsu.js
- src/parser/jobs/nin/modules/TrickAttackUsage.js
The meme opener for NIN on fights where the boss gets pulled far enough into middle includes a prepull Doton before the Hide reset into Suiton. The module was dinging on it when there's no harm in getting free damage, so this fixes that.
> Added a check in the Ninjutsu module to forgive prepull STDs

- src/parser/core/modules/Interrupts.tsx
Honestly, this never came up during testing with casters :blobsweat:; those pesky melee always bringing up those edge cases.
> Fix attack actions counting as interrupts

- locale/en/messages.json
- src/parser/jobs/pld/index.tsx
- src/parser/jobs/pld/modules/FightOrFlight.tsx
- src/parser/jobs/pld/modules/NOTES.md
- src/parser/jobs/pld/modules/Requiescat.tsx
This PR makes some minor changes to PLD recommendations and (due to the lack of major changes) marks PLD as supported through 5.2.
Change details:
- Fight or Flight now recommends fitting 11 GCDs rather than 10 to reflect best practices.
- Requiescat now only complains about sub-3-Holy Spirit windows, to reflect the frequent utility of a 60s PLD rotation which drops a Holy Spirit every minute.
> PLD 5.2 updates

- locale/en/messages.json
- src/parser/jobs/pld/modules/FightOrFlight.tsx
The copy for FoF was not properly updated to account for the change to 11-GCD FoF in #855 .
This fixes the issue.
> Fixes a minor error in the FoF copy.

- src/parser/core/modules/BuffWindow.tsx
Implementors can override generateBuffNotUsedOutput to give alternate output and/or generate a suggestion in this case.
> Ssuppress BuffWindow module output if buff is never used

- src/components/Find/FightItem.js
- src/components/GlobalSidebar/Breadcrumbs.js
- src/components/ui/RotationTable.tsx
- src/parser/core/Parser.tsx
- src/parser/jobs/rdm/modules/MeleeCombos.js
- src/utilities/strings.ts
This also changes the behavior of formatDuration for pre-pull timestamps to show <0s rather than -01:-01
> Unify the utilities function formatDuration with parser.formatDuration

- src/data/STATUSES/root/WHM.ts
Asylum is using an older ID; it gets changed to a new one at 78 because of the new trait.
> Update Asylum ID

- src/components/ui/RotationTable.tsx
- src/parser/core/Parser.tsx
- src/utilities/strings.ts
- Pass the secondPrecison option from parser.formatDuration to the function, so that the option is actually respected (whoopsie daisy) - restores original behavior
- Add a parameter for showNegative to control whether to format and return the actual negative amount or to return `< 0s` for negative numbers.  Along with this, fix the rounding for minutes so that it rounds in the correct direction on negative numbers, and fix showing -00:-15 if a longer duration.
- Since all of our default option values are falsey, actually make all of the options optional.
- Fix RotationTable so it requests 0 decimals precision for seconds (which it was getting previously with the way the string function behaved), so early windows show as 00:01 instead of 00:01.25, in line with the rest of the table
> FormatDuration cleanup & fixes

- src/parser/core/modules/Interrupts.tsx
What it says on the tin, except there's now a method to provide alternative output as well. Also, corrected an issue which technically would lead to chaos if someone tried to use ts to provide suggestion why content.
> Suppress interrupt table output if there's no interrupts

- locale/en/messages.json
- src/data/ACTIONS/root/NIN.ts
- src/parser/jobs/nin/modules/Huton.js
As of 5.1 NIN no longer has three combos. The only other skill suggestion would be Aeolian Edge.
> [NIN] Change Huton clipping suggestion to align with 5.1 combo changes

- src/parser/jobs/smn/modules/EgiCommands.tsx
This check ignores issued egi commands that were fabricated by CDDT (`type === AbilityType.special`). It has the effect of fixing this bug in prod:
> SMN - add check to onCommandIssued for fabricated egi commands

- src/parser/core/Module.ts
- src/parser/core/modules/Swiftcast.tsx
- src/parser/jobs/smn/modules/DWT.js
- src/parser/jobs/smn/modules/EgiCommands.tsx
- src/parser/jobs/smn/modules/Swiftcast.js
* Added helper method to Swiftcast that's much like it's parent class that allows users to filter out swiftcasts.
* Modified the SMN-specific implementation of swiftcast to filter out casts during DWT. To do this, I'm pretty sure I just read a book on necromancy (or figured out some of the pain SMN devs have to go through) to figure out how DWT worked.
* Modified DWT to export DWT_CAST_TIME_MOD so it only has to be edited in one place instead of every file (do we have a 'job constants' file somewhere?)
* Was a good dev and disabled debug mode on EgiCommands.tsx when I saw that someone had left it enabled
> Fix SMN going turbomode during DWT and swiftcast

- src/parser/jobs/mch/index.js
- src/parser/jobs/mch/modules/Drift.tsx
- src/parser/jobs/mch/modules/GeneralCDDowntime.tsx
- src/parser/jobs/mch/modules/MultiHitSkills.ts
- src/parser/jobs/mch/modules/index.js
- AoE usages suggestion:
- AoE usages table:
- Bioblaster sharing a recast with Drill accounted for in Drift module:
> MCH - add AoE usages module, add Bioblaster to Drift 

- src/parser/jobs/blm/index.js
- src/parser/jobs/blm/modules/RotationWatchdog.tsx
Currently the jp Opener is shown as bad on the watchdog, despite being a recommended opener in quite a big SpS range. This fix gets rid of the false negative
> BLM: Fix RotationWatchdog to stop flagging Jp Opener

- src/data/ACTIONS/root/NIN.ts
Turns out there are 3 different versions of TCJ Fuma, one for each mudra, and it throws off the Trick window module when one of the two that wasn't there is used. SE pls.
> Updated NIN data files for two additional TCJ Fuma variants

- src/parser/core/modules/NormalisedEvents.ts
- src/parser/jobs/dnc/changelog.tsx
- src/parser/jobs/dnc/modules/Technicalities.tsx
Some of the normalized buff events that pass through from countTechBuffs were hitting other actors somehow, which was in some cases (found with this report: https://www.fflogs.com/reports/Q9g8P4n6VktfWzCw#fight=6&source=3) causing an extra technical finish window to 'open' inappropriately, and also potentially tripping the 'there's another dancer here' check because of it.
Updating the tryOpenWindow function to exclude those events, and correcting the source<->player ID comparison.
Also noticed I derfed the year for the multi-dnc changelog entry in one of the merges somehow...
> BugFix Tech Window opening when player not in the targets

- src/data/ACTIONS/root/NIN.ts
- src/parser/jobs/nin/index.js
- src/parser/jobs/nin/modules/OGCDDowntime.js
- src/parser/jobs/nin/modules/index.js
What it says on the tin. Also, to address one question before it gets asked; I deliberately excluded Shadow Fang from the CDDT module (at least for now) because its cooldown is affected by Huton. Since we aren't properly accounting for that in calculations, it acts as though it's 70s no matter what and throws off the math.
> Add a CooldownDowntime module to NIN

- src/data/ACTIONS/root/MCH.ts
- src/parser/jobs/mch/modules/Cooldowns.js
Detonator now shows up on the timeline and as an incorrect weave (when applicable). Doesn't appear to affect any other MCH modules. Here's a log where detonator is weaved incorrectly (2:48 weave window): https://www.fflogs.com/reports/fHgM438FwAXWt9KJ
> MCH: add detonator to actions

- src/parser/jobs/drg/index.js
- src/parser/jobs/drg/modules/Drift.tsx
Currently this module breaks if a log is posted of synced down/lower level content or a log that does not have any casts of HJ or GSK. Added a simple check that will bypass creating said table/only create the table for the correct skills to avoid showing an error. Useful for stuff like UWU and UCoB where HJ is synced down to Jump.
> Fix to avoid Ability Drift breaking on No Casts of HJ/GSK.

- src/parser/jobs/sam/modules/Meikyo.tsx
Sam has a bug currently that the default end of fight rushing can make the expected GCDs go negative. this PR fixes that problem.
There is however currently a minor problem in the way I reduce the GCDs. If a samurai uses Meikyo in the beginning of the weave window, the time stamp for the buff can sometimes cause the system to think they can get an extra GCD when in reality they can not. I'm unsure of how I can fix that at the moment and would love some ideas.
> [Bug Fix][Sam] Meikyo Window End of Fight rushing

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/parser/jobs/mnk/modules/Fists.tsx
- src/parser/jobs/mnk/modules/RiddleOfFire.tsx
When players pull in RoW (or any other Fist, or none really) and never change over the fight, we're unable to detect precisely what Fist they're in. This PR adds a suggestion for when we don't know, and updates the stats block for Fists and Table for RoF with the relevant information.
> Knoweth thy Fist

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/parser/jobs/drg/modules/BloodOfTheDragon.js
- src/parser/jobs/drg/modules/OGCDDowntime.ts
With GSK in the OGCD tracker, the old suggestion to keep GSK uses close to High Jump uses is no longer needed.
> DRG: Adjust first use offset, remove old suggestion

- src/parser/jobs/smn/modules/Devotion.js
With two Summoners, the window would show skills cast during the other Summoner's Devotion.
> Fixed double Devotion issue

- src/data/ACTIONS/root/NIN.ts
- src/parser/jobs/nin/modules/TrickAttackUsage.js
- src/parser/jobs/nin/modules/TrickAttackWindow.js
What it says on the tin. I also refactored `TEN_KASSATSU` to `TEN_NEW` since my assumption about when 18805 gets used over 2259 doesn't apply to Chi and Jin and I'd rather keep their names consistent.
> Add in the old IDs for Chi and Jin to fix buggy timelines

- src/data/ACTIONS/root/MRD.ts
- src/data/ACTIONS/root/WAR.ts
- src/parser/jobs/sam/modules/Sen.tsx
Fixed a bug that was, err, bugging me.
Before:
(00:31, 03:06, 03:16, 03:20 were all combo'd tempests)
After:
(finished combos are no longer showing, also overpower combo breaks are now showing correctly, nice)
Log: https://www.fflogs.com/reports/aQRgcM8fXK41xrVz#fight=10&type=casts&source=3&view=events
> WAR - added combo to mythril tempest

- src/parser/jobs/drg/modules/Positionals.js
Simulated charges weren't giving enough of a buffer to account for TN being used on CD. Changed from 200 ms to 500 ms.
Demonstrated by this log: https://www.fflogs.com/reports/7zhtR1q3Hpfcg6rD#fight=43&source=56
> DRG: Adjust true north recharge buffer

- src/parser/jobs/drg/modules/BloodOfTheDragon.js
Before suggesting a delay, the module now checks to make sure a full delayed window can actually happen (as in there are at least 60 seconds left in the fight). Checking for possibility of a max duration delayed window prioritizes casts of Nastrond over buffing 1-3 casts.
> DRG: Fix LotD module showing a warning to delay past end of fight

- src/parser/jobs/mch/index.js
- src/parser/jobs/nin/index.js
No changes to the jobs in the patch notes, ez version bump.
> Flag NIN and MCH as supported for 5.3

- src/parser/jobs/sch/index.js
Obviously don't merge right away, but changing the MP usage on succor doesn't break any existing analysis.
> Support for 5.3 added on SCH

- src/parser/jobs/drg/index.js
No patch notes, no problem. No changes to DRG in 5.3 so we're good over here.
> DRG: mark supported for 5.3

- src/data/ACTIONS/layers/patch5.3.ts
- src/parser/jobs/mnk/index.tsx
- src/parser/jobs/mnk/modules/Gauge.ts
Mince, L'PR est Australienne (no Miu's were hurt in the typing of this message).
PB to 90s, Form Shift no longer requires you to be a Coeurly boi. Keeping support for pre-5.3 tho.
> MNK 5.3 support

- src/components/ui/RotationTable.tsx
- src/parser/core/modules/BuffWindow.tsx
- src/parser/jobs/war/modules/InnerRelease.tsx
For rotation target outcomes that don't follow the default pattern of ">= threshold good, else bad", RotationTarget accessors may optionally provide a custom comparator function defining the criteria for positive/negative usage highlighting. Existing behaviour for highlighting is used by default. Also added a method `changeComparisonClassLogic(buffWindow, action)` to BuffWindow that implementing modules can use as in the following example:
```typescript
export default class SomeBuff extends BuffWindowModule {
// ...
private someActionOutcome(actual: number, expected?: number): RotationTargetOutcome {
return {
// positive ONLY if actual uses is exactly equal to expected
positive: expected === undefined ? false : actual === expected,
// never negative
negative: false,
}
}
protected …
```
> RotationTable - add optional comparator function for cell highlighting

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/parser/core/modules/BuffWindow.tsx
- src/parser/jobs/mch/index.js
- src/parser/jobs/mch/modules/Tincture.tsx
- src/parser/jobs/mch/modules/index.js
Adds a separate event hook for pet casts in BuffWindows. This hook is ignored unless an optional `petActions: Action[]` exists and is non-empty. These actions will be considered in the rotation section of the table, and can also be added to trackedActions if desired (here we're tracking Pile Bunker since it's by far the biggest flexible damage cd MCH has).
> MCH - Tinctures

- src/parser/jobs/brd/modules/ApexArrow.tsx
Turns out hitCount includes ghosted hits, so it could sometimes be nonzero while still having no confirmed events. Fixes the error for the two sentry logs that had ghosted apex casts.
> BRD - Apex Arrow bugfix 

- src/parser/core/modules/PrecastStatus.js
Updates combatantactions with observed cast events so we don't synth casts that actually happened post-pull.
> [BugFix] PrecastStatus - Round 2

- src/parser/core/modules/BuffWindow.tsx
- src/parser/jobs/mch/modules/Tincture.tsx
Uses layered action data now. Also added a buffer for the tincture buff application on fight start / downtime to deal with the case where a tincture is used prepull but the buff doesn't apply until postpull. Ideally I'd like to be able to track reassembled GCDs themselves instead of reassemble casts, but that would involve tearing up a lot of BuffWindow code so this'll do for now.
> MCH - Tincture improvements

- src/parser/jobs/drg/modules/OGCDDowntime.ts
DRG opener recently recommended pushing back jumps by two GCDs, so the first use offset is a little too tight now. When reviewing this change, I noticed that the 2s buffer put in for parser timing wiggly-ness for buff use wasn't added to jumps or life surge, so I put it back.
New first use timings with 2.5s GCD:
- Jumps: 22.5s (before 9th GCD) + 2s buffer = 24.5s
- Life Surge: 20s (before 8th GCD) + 2s buffer = 22.0s
> DRG: OGCD Downtime changes for adjusted opener

- src/parser/jobs/rdm/index.js
- src/parser/jobs/rdm/modules/Dualcast.js
Per Meru updated the severity rating for missed Dual Casts shifting values down one and dropping minor as missing is never considered minor.
> Dualcast severity update for missed casts.

- locale/en/messages.json
- src/parser/jobs/ast/modules/Draw.tsx
> AST - Remove errant space in translation

- src/parser/jobs/brd/modules/ApexArrow.tsx
Fixes a tricky edge case with apex arrow where the 1st confirmedEvent does 'very low damage' (usually due to immunity) but subsequent hits don't.
> BRD - if apex hits multiple targets, choose the best hit for potency calcs

- src/parser/jobs/ast/index.tsx
- src/parser/jobs/ast/modules/EarthlyStar.tsx
We weren't ever incrementing uses, which was the main issue.
Also copy the logic from Draw for calculating lost time if it stopped being used at some point during the fight.
Fixes issue reported on discord.
> AST - Fix Earthly Star counts

- src/data/ACTIONS/root/ROLE.ts
> Fix Provoke cooldown duration

- src/data/ACTIONS/root/ARC.ts
Currently there's a bug where almost every bard log will have a synthed Heavy Shot cast at the beginning of the timeline because the status Straight Shot Ready is applied by many actions, but only Heavy Shot has SSR as an applied status in the data files. Adding SSR to all the relevant actions doesn't solve the problem because of the way PrecastStatus looks for corresponding statuses, and anyway there is no current need for SSR being tracked as an applied status, so this bandaid fix seems appropriate for now.
cc @AzariahAeroborn
> BRD - PrecastStatus Bug Fix

- src/data/ACTIONS/layers/index.ts
For some reason, patch 5.3 actions layer was never added to the layers index so these changes weren't actually being used. Ay feex.
Looks like 5.2 only had potency changes, so while we have that data, nothing seems to actually use it for the affected jobs and so there's no layer for it.
> Add patch 5.3 actions layer to the index

- src/data/PATCHES.ts
Changed the time in the comment for 5.3 global too, it was written as BST but labelled GMT. Patch times for global are actually based on JST but that's useless for anyone reading the document to use as an easy reference.
CN 5.3 is this Tuesday, December 1st as per https://ff.web.sdo.com/web8/index.html#/newstab/newscont/323473
Global 5.4 is next Tuesday, December 8th, as per https://eu.finalfantasyxiv.com/shadowbringers/patch_5_4
> Add dates for global 5.4 and CN 5.3 patches

- src/data/ACTIONS/root/AST.ts
- src/parser/jobs/ast/index.tsx
- src/parser/jobs/ast/modules/Sect/Sect.tsx
Fixes #1045
The incorrect ID appears to be Diurnal's Aspected Benefic. I created [this minimal log](https://www.fflogs.com/reports/26y8HKtg97WfZzDC) with a few casts in each sect to verify. The first encounter is in Nocturnal, the second is Diurnal.
After updating the diurnal id, the casts appear in the timeline for me in both sects.
I found some mismatched buffs in the sect detection module while tracking this down, so I corrected those as well.
> Fix Aspected Benefic's ability id

- src/data/ACTIONS/layers/index.ts
- src/data/ACTIONS/layers/patch5.4.ts
- src/data/ACTIONS/root/ROG.ts
- src/parser/jobs/mch/index.js
- src/parser/jobs/nin/index.js
Updated the potencies on Spinning Edge/Gust Slash per the patch notes, but neither job has any other changes whatsoever.
> Mark NIN and MCH as supported for 5.4

- src/parser/jobs/sam/index.js
Much like the SAM modules on XIVA the last few months, nothing has changed for SAM.
> Mark SAM as supported for 5.4

- src/data/ACTIONS/layers/patch5.4.ts
- src/parser/jobs/drg/index.js
Just potency changes this time around.
> DRG: Update potencies and mark support for 5.4

- src/parser/jobs/drg/modules/Drift.tsx
Fixes hard crash on instances where `downtime.isDowntime()` returns true, but `downtime.getDowntimeWindows()` returns nothing. Doesn't fix the root cause, but now checks for the existence of a window and falls back to assuming there is no downtime if the window isn't defined.
> DRG: Fix hard crash on drift error

- src/data/BOSSES.ts
- src/parser/AVAILABLE_MODULES.ts
- src/parser/bosses/e12_1/index.ts
- src/parser/bosses/e12_1/modules/Invulnerability.ts
- src/parser/bosses/e12_1/modules/index.ts
- src/parser/bosses/exEmerald1/index.ts
- src/parser/bosses/exEmerald1/modules/Invulnerability.ts
- src/parser/bosses/exEmerald1/modules/index.ts
- src/parser/bosses/exEmerald2/index.ts
- src/parser/bosses/exEmerald2/modules/Invulnerability.ts
- src/parser/bosses/exEmerald2/modules/index.ts
- src/parser/core/modules/Invulnerability.tsx
Title.
Also tweaks core implementation so debug mode will print names/guids for ephemeral actors, which was a bit of a hold up in dev-general re: emerald.
Gorgeous
> Remaining invuln config for 5.4 content

- src/parser/jobs/drg/modules/Drift.tsx
Turns out we should just use `getDowntimeWindows` correctly and then we won't have errors. Leaving in the safety check just in case. Thanks to Kelos for pointing this out.
> DRG: actually fix drift error

- src/parser/jobs/brd/modules/ApexArrow.tsx
Fixes a little bug where apex arrows that overkill are treated as low damage.
> BRD - Don't flag apex if it was overkill

- src/parser/jobs/sam/modules/DISPLAY_ORDER.js
- src/parser/jobs/sam/modules/Higanbana.js
- src/parser/jobs/sam/modules/Kenki.js
- src/parser/jobs/sam/modules/Meikyo.tsx
- src/parser/jobs/sam/modules/Sen.tsx
- src/parser/jobs/sam/modules/Shoha.tsx
What is this, 2018? SAM has Display Order now.
Current Logic for display order in my head is:
1) Checklists
2) Suggestions
3) Stats that can be changed/ could have obvious errors (Dots, Buff Windows, etc.)
4) Stats like gauge amount and stacks of Shoha, This in my head is the normal "End of page" for SAM focused critique/Information
5) Things such as interrupted Casts that were stated as a suggestion before that are now expanded in detail.
I'm not sure if I should flip the last 2 slots though
> [SAM] Sam Display Order

- src/data/ACTIONS/root/SMN.ts
I believe this is just a longstanding typo from #636 since I can't find any justification for attaching Everlasting Flight to Enkindle Phoenix. Paging @ackwell just in case there's a good reason for having it this way that I missed.
Fixes a bug where PrecastStatus synths a cast of Enkindle Phoenix at the start of the timeline of most SMN logs.
> SMN - Move EF statusApplied from enkindle to FBT

- src/parser/jobs/dnc/DISPLAY_ORDER.ts
- src/parser/jobs/dnc/modules/Weaving.ts
- src/parser/jobs/dnc/modules/index.ts
Since the GCD of dance finishes is 1.5s, double weaving after a dance will certainly cause clipping and is thus discouraged.
> DNC - flag double weaves after a finish as weaving issues

- src/parser/jobs/dnc/modules/Weaving.ts
- src/parser/jobs/mch/modules/Weaving.ts
- src/parser/jobs/mch/modules/index.js
Sequel to #1086, these GCDs have a fixed 1.5s recast and we really really don't want to double weave after them.
> MCH - flag double weaves after a hypercharge GCD as weaving issues

- package.json
- src/data/ACTIONS/index.ts
- src/data/STATUSES/index.ts
- src/parser/core/__tests__/filter.ts
- src/parser/core/filter.ts
- src/parser/core/modules/Data.ts
- yarn.lock
Adds a the primary filter builder, following a fluent-esque api. Also adds the `oneOf` helper (for matching against one of a number of options), and extensions of `oneOf` for action/status keys in `core/Data`.
> Add filter builder helper

- src/data/ACTIONS/root/MCH.ts
- src/data/STATUSES/root/MCH.ts
Currently the detrimental (DoT) wildfire status is listed as the corresponding action's applied status. This PR replaces it with the beneficial status.
Before:
After:
> MCH - Fix Wildfire status in timeline

- src/data/ACTIONS/root/PLD.ts
Total Eclipse wasn't starting the combo correctly, making all usages of TE and Prominence result in an `Uncomboed` Prominence within the analysis
> fix(pld.ts): total eclipse now starts a combo for prominence

- src/parser/jobs/sch/modules/Aetherflow.js
+ Drift for aetherflow casts was incorrectly calculated when followed by dissipation
+ Recitation pre-pull usage was counted as an extra aetherflow usage
+ Wasted aetherflow usages weren't calculated for when dissipation was cast while there were remaining aetherflow stacks
> Fixes to a couple of issues with the SCH Aetherflow Module

- src/parser/core/modules/BuffWindow.tsx
- src/parser/jobs/brd/modules/RagingStrikes.tsx
- src/parser/jobs/mch/modules/Tincture.tsx
Adds an optional status field to BuffWindowTrackedActions. When this field is present, usages are counted by RemoveBuff events rather than CastEvents. This allows for actions like Reassemble and Barrage to behave properly as trackedActions (the necessary changes for both are also included in this PR).
Before:
After:
https://xivanalysis.com/fflogs/zjtxA4GQLZgkC2Ph/10/8
> BuffWindow - handle simple statuses as tracked actions

- src/parser/core/modules/CooldownDowntime.tsx
Simple change that allows job implementations to optionally specify a weight for each cooldown group.
> CDDT - Allow cooldown groups to be assigned weights

- src/parser/jobs/dnc/modules/OGCDDowntime.tsx
Since these abilities behave like GCDs in practice, and since drifting them is heavily discouraged, the default 1250ms allowed downtime is too lenient and frequently produces logs such as the one below. This PR reduces the allowed downtime to 250ms.
> DNC - stricter downtime forgiveness for Technical / Standard Step

- src/event.ts
- src/reportSources/legacyFflogs/__tests__/__snapshots__/eventAdapter.ts.snap
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/adapter.ts
- src/reportSources/legacyFflogs/eventAdapter/base.ts
- src/reportSources/legacyFflogs/eventAdapter/deduplicateActorUpdates.ts
- src/reportSources/legacyFflogs/eventAdapter/deduplicateStatus.ts
- src/reportSources/legacyFflogs/eventAdapter/index.ts
- src/reportSources/legacyFflogs/eventAdapter/translate.ts
This PR modularises the event adaption pipeline slightly, making it easier to perform transformations on the events before they move into the parser.
This system is effectively the new event system's replacement for the old normalisation system.
In addition, it:
- Adds the new `bearing` position data to actor updates
- Merges duplicate `statusApply` events caused by fflog's apply -> applystack crap
- Omits redundant `actorUpdate` data
> Improve event adaption pipeline

- src/parser/jobs/gnb/modules/Ammo.tsx
Adding two features for the gunbreaker - 
1. Showing source for the ammo timeline.
2. Having "waste" or "overcap" part of the timeline, so players could see when it happend.
I am not sure how good the code is, would love to have some help with that to make it more maintain-able
but it does the work.
I can add comments if it helps.
This is how it looks:
Generator: https://cdn.discordapp.com/attachments/808985736962506752/809188772217880586/unknown.png
Spender: https://cdn.discordapp.com/attachments/808985736962506752/809188810121805884/unknown.png
Overcap Before: https://cdn.discordapp.com/attachments/808985736962506752/809188855710089286/unknown.png
Overcap After: https://cdn.discordapp.com/attachments/808985736962506752/809188883283443712/unknown.png
> GNB: Cart Timeline Update (Overcap + Extra Info)

- src/parser/core/modules/BuffWindow.tsx
For whatever reason, logs are not behaving like they used to and statuses that apply to GCDs aren't always fading at the same time as the GCD was cast. This PR adjusts the logic for counting expired statuses by checking for a GCD use that was within the buffwindow with a timestamp less than or equal to the status fade timestamp.
> BuffWindow - status counting bugfix

- src/parser/core/modules/BuffWindow.tsx
- src/parser/jobs/nin/index.js
Fixes the duplicated TA window ~4:30 in E10S.
I added a changelog entry since this is a bug that has been reported by users a few times, but I'm not attached to it if we want to silently fix instead.
> Corrected cases where Trick Attack windows could be improperly split.

- src/reportSources/legacyFflogs/__tests__/__snapshots__/eventAdapter.ts.snap
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/adapter.ts
- src/reportSources/legacyFflogs/eventAdapter/base.ts
- src/reportSources/legacyFflogs/eventAdapter/prepull/action.ts
- src/reportSources/legacyFflogs/eventAdapter/prepullAction.ts
- src/reportSources/legacyFflogs/store.ts
Adds a new fflogs adapter step that synthesizes 'action' events for actions used pre-pull. The old version (PCA) needs to stay for now since it's still depended on by legacy modules.
> Adapter step for precast actions

- src/parser/core/modules/Weaving.js
Events synthed as precast shouldn't affect the weave count, since they happened before the first damage event. Kick out any events with a timestamp earlier than the beginning of the fight.
> Ignore precast events when counting weaves

- locale/en/messages.json
- src/parser/jobs/blm/index.js
- src/parser/jobs/blm/modules/Weaving.js
1. The JP opener (both versions) require a single clipped Triplecast weave after the first Fire IV. Converting the 'Opener Enochian' check to work for both of these skills, since they have the same opener considerations.
2. The About description for the BLM module had a busted action link in it. Switching from TransMarkdown to Trans to resolve that.
> Allow one Triplecast weave in JP opener & fix BLM description actionlink

- src/data/__tests__/getDataBy.ts
- src/data/getDataBy.ts
- src/parser/core/modules/PrecastStatus.js
Adds a new function, `getDataArrayBy` with the same signature as gDB except it returns all matches instead of just the last one. Also includes a safeguard against a bug with `precastStatus` that occurs when there are multiple actions in data that apply the same status.
> Modify getDataBy to return all matching entries

- src/parser/core/modules/CooldownDowntime.tsx
- src/parser/core/modules/DoTs.js
- src/parser/core/modules/EntityStatuses.ts
- src/parser/core/modules/GlobalCooldown.js
- src/parser/core/modules/Invulnerability.tsx
- src/parser/core/modules/UnableToAct/UnableToAct.tsx
- src/parser/jobs/ast/modules/SleeveDraw.js
- src/parser/jobs/blm/modules/Gauge.js
- src/parser/jobs/brd/modules/AlwaysBeCasting.ts
- src/parser/jobs/brd/modules/PitchPerfect.js
- src/parser/jobs/brd/modules/SongUptime.js
- src/parser/jobs/dnc/modules/DirtyDancing.tsx
- src/parser/jobs/drg/modules/BloodOfTheDragon.js
- src/parser/jobs/drg/modules/Drift.tsx
- src/parser/jobs/pld/modules/FightOrFlight.tsx
- src/parser/jobs/pld/modules/Requiescat.tsx
- src/parser/jobs/sam/modules/Higanbana.js
- src/parser/jobs/smn/modules/Ruin2.js
- src/parser/jobs/whm/modules/DoTs.js
Title. Tin. Etc.
This PR audits every call to `downtime`, `unableToAct`, and `invuln` that I could find, fixing any logic that relied on their ability to "see the future" due to normalisation.
I've also put in some errors if anything else tries to do it, which'll hopefully be caught by sentry if I missed something.
I'm not going to pretend I know the intricacies of every job. I took care to avoid changing logic too much, but it's impossible to avoid in some cases. I may well have broken your job. Please check the code for your modules!
I'll be adding some comments below shortly.
> Audit & remove look-ahead downtime checking

- src/parser/core/Parser.tsx
- src/parser/core/modules/Downtime.tsx
- src/parser/core/modules/UnableToAct/UnableToAct.tsx
- src/parser/core/modules/UnableToAct/index.ts
- src/parser/core/modules/index.js
- src/parser/jobs/ast/modules/SleeveDraw.js
- src/parser/jobs/blm/modules/Gauge.js
- src/parser/jobs/blm/modules/NotCasting.js
- src/parser/jobs/blm/modules/RotationWatchdog.tsx
That diff is... gnarly. git pls. It's basically a total rewrite, probably better looking at it without the diff.
This PR:
- "Ports" `UnableToAct` to the new analysis system
- Adds a few nice-to-have APIs to it for direct access w/o going through downtime
- Adds some deprecated-out-of-the-gate functions to the parser to assist with converting timestamps between the two systems.
> Port UnableToAct to Analyser

- src/data/ACTIONS/layers/index.ts
- src/data/ACTIONS/layers/patch5.5.ts
- src/data/PATCHES/patches.ts
- src/data/STATUSES/layers/index.ts
- src/data/STATUSES/layers/patch5.5.ts
Layers are empty however DRG and WAR need the actions layer, and MNK needs the statuses one. SCH doesn't appear to use the mpCost so that won't need a layer update I guess.
> Add patch 5.5

- src/parser/jobs/sch/index.js
I mean, it's 100 mp cost. We don't even do mp-based analysis on SCH.
> Update SCH for 5.5 support

- src/data/STATUSES/layers/patch5.5.ts
- src/parser/jobs/mnk/index.tsx
- src/parser/jobs/mnk/modules/RiddleOfFire.tsx
- src/parser/jobs/mnk/modules/TwinSnakes.tsx
Plus bug fixes raised in fb-monk on Discord. ST pre-RoF in opener is largely unavoidable so bumping the trigger to 2 bad ST's over the fight. Twin is a bit more complex, a user finished a combo, hit 6SS, then LB, which forced their next combo to refresh Twin. The timing was correct but the GCD count wasn't, so I've converted the module to ding on any refresh above 6s remaining on the status.
> Patch 5.5 support for MNK

- src/parser/jobs/rdm/index.js
- src/parser/jobs/rdm/modules/GeneralCDDowntime.ts
It's no longer suggested to use SwiftCast on CD for a RDM so removing it from the General CD tracking list.
> Remove SwiftCast from tracked CDs

- src/parser/jobs/smn/index.js
DoT nerf suspiciously missing from patch, but that wouldn't have affected analysis anyway.
> Mark SMN patch 5.5 support.

- src/parser/jobs/pld/index.tsx
PLD is unchanged in 5.5, so no logic changes are needed.
> Bump PLD support to 5.5

- src/parser/bosses/e8/modules/Invulnerability2.ts
- src/parser/bosses/e8/modules/index.ts
- src/parser/bosses/exVaris/modules/Invulnerability2.ts
- src/parser/bosses/exVaris/modules/index.ts
- src/parser/core/__tests__/filter.ts
- src/parser/core/filter.ts
- src/parser/core/modules/Actors/Actor.ts
- src/parser/core/modules/Death.tsx
- src/parser/core/modules/Invulnerability2.tsx
- src/parser/core/modules/index.js
- src/report.ts
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/deduplicateActorUpdates.ts
- src/reportSources/legacyFflogs/reportAdapter.ts
This PR:
- Implements the core logic of tracking invulnerability windows at runtime using the new event system
- Adds the concept of an actor "kind"
- makes the deduplication adapter more typesafe
- adds the `exists` filter (lmao)
It does _not_ implement a public API for the new invulnerability module, nor does it actually replace the old with the new. That will be done in a follow-up.
This new module, due to the constraints imposed by pulling the logic into the primary parser runtime, now throws an error at a point where the old module could sanely backfill data.
I've added logic to pre-emptively fill the data that would previously be backfilled, and it seems to function correctly, but I want to leave this running in the background for a short while to make sure I've caught all the edge …
> Port invulnerability to new event system, part 1

- src/parser/jobs/mnk/modules/Fists.tsx
Fixes this "bug"; since it's already assuming flame fisties for the full duration we might as well call it 100% uptime too.
> MNK - assume 100% uptime when fist is unknown

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/parser/core/Parser.tsx
- src/parser/core/modules/BrokenLog.tsx
- src/parser/core/modules/Death.tsx
- src/parser/core/modules/Dummy.tsx
- src/parser/core/modules/index.js
Because dummies just... break things. A lot.
Also "just" updates `death` to handle non-active-player deaths which ended up as half a rewrite.
> Add striking dummy detection module

- src/parser/jobs/dnc/modules/Gauge.tsx
This fixes the sentry logged with the new Feather/Esprit gauges from a 24 man that had carry-forward feathers spent before any generators.
https://xivanalysis.com/fflogs/9cr83VNbzAkGaDfq/10/18
> Also check init events when fudging

- src/parser/jobs/blm/modules/RotationWatchdog.tsx
PR #1130 added a new FIRE_IV_CAST_TIME_MILLIS const, but was done before the recent conversion to use millis for Action cast times, which got overlooked in review
Result was basically every Fire IV rotation that was missing F4s was subsequently tripping the 'you couldn't have gotten more F4s in' because it was looking at the ~45 minute mark to see if the boss was invulnerable instead of mere seconds after the cycle ended, thanks to the extra three orders of magnitude on that value
> Bugfix: BLM - Don't milli the milli

- src/parser/core/Analyser.ts
- src/parser/core/Debuggable.ts
- src/parser/core/Injectable.ts
- src/parser/core/Loggable.ts
- src/parser/core/Module.ts
- src/parser/core/Parser.tsx
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/base.ts
This was originally done in support of #1180, but I pulled it out for ~~ease of review~~ simplicity of troubleshooting the type errors I had.
I verified against https://xivanalysis.com/fflogs/F8ZfDGXrkbajxhYR/19/1258 that the broken log triggers were still generating the same output with the change to Parser._gatherErrorContext.
> Refactor Debug logging to a module that can be shared with Analysers

- src/event.ts
- src/parser/core/modules/EventsView/eventFormatter.tsx
- src/reportSources/legacyFflogs/__tests__/__snapshots__/eventAdapter.ts.snap
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/prepullAction.ts
- src/reportSources/legacyFflogs/eventAdapter/translate.ts
Update the new system to invert the snapshot -> damage/heal paradigm to be damage/heal -> execute instead, to more accurately match how the game data handles it and simplify the interface for future consumers (e.g. gauges)
> Change semantics of snapshot vs execute for damage/heal actions

- src/reportSources/legacyFflogs/__tests__/__snapshots__/eventAdapter.ts.snap
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/translate.ts
What the title says.
This acts under the assumption that _everything_ prior to 5.08 has no `calculatedX` events, and noops them to be doubly sure.
It then treats all `damage` and `heal` events (as opposed to `calculateddamage` and `calculatedheal`) as the primary effect, and fabricates an immediate execute event.
This should effectively maintain the semantics of xiva's event model with... _reasonable_ back compat with old stuff. Reasonable enough to not crash and provide semi-sane output, at least.
> [Bugfix] Synth executes for damage events prior to the FFLogs calculated damage update

- locale/en/messages.json
- src/parser/jobs/smn/modules/Pets.js
Prevents the pet summon normaliser from `break`ing prematurely when a summon event is detected from a summoner other than the selected player. Also removes an outdated reference to "keeping your pet out of boss AoEs", since pets can't die anymore.
> SMN - more summons, more problems

- src/event.ts
- src/parser/core/modules/EventsView/eventFormatter.tsx
- src/parser/jobs/blm/modules/Procs.tsx
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/adapter.ts
- src/reportSources/legacyFflogs/eventAdapter/interrupts.ts
Title. Cast interruption/cancellation is a discrete concept in the game (pretty sure it's an ActorControl packet or similar), and is even logged by ACT. Unfortunately it isn't exposed by fflogs, so here we are, fabricating it. Great.
I'm opting to keep both a source and target field on this event, as realistically, interruptions _are_ targeted. Movement and explicit cancellation is self -> self, but players can interrupt some boss abilities, and (at least in the past?) bosses can interrupt us with damage.
> Add new interrupt event to core structure

- src/parser/jobs/blm/modules/RotationWatchdog.tsx
Depending on the exact ordering of the MP status updates vs the rotation starting, opener MP can come in as 8000, which is below our 'Max MP for full rotation' threshold. That doesn't mean you'll actually be missing fires however...
Similarly, thunder spam under ice shouldn't _really_ flag as 'extra hardcast t3s' since that metric is about losing Fires because of it, which isn't the case for ice phase thunders.
There's probably some better calculation work we can put into the 'did you hardcast more T3s than you should have?' logic, but for right now, just including a backstop of checking if you got all your fires should resolve the bug.
> BLM - Don't flag rotations with all expected fires as having 'extra T3's

- locale/de/messages.json
- locale/en/messages.json
- locale/fr/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/zh/messages.json
- src/data/ACTIONS/root/WHM.ts
- src/parser/jobs/whm/modules/Thinair.tsx
- src/parser/jobs/whm/modules/index.js
Add module to track Thin Air mana usage. Kinda what is suggested in #600, but scanning for a specific spot of time to use thin air doesn't feel quite right as rotations are different per fight and giving specific 'use thin air here' advice doesn't sit quite well with me. 
For now this just tracks each usage of thin air and how much MP they save each. Maybe add something about total MP saved and missed usages?
Edit: also please help test that the MP calculation is correct. In theory this only counts casts completed while thin air is active but that may be buggy because I don't know how the codebase actually works :/
> WHM: Thin air MP tracking module

- src/reportSources/legacyFflogs/component.tsx
Fixes the apparent discrepancy between fflogs' `fight=last` pull ID and the one xiva chooses when there are trash pulls that come later than the last non-trash pull.
> Filter trash pulls from fflogs "last fight" redirect

- src/data/ACTIONS/root/DNC.ts
Adds the corresponding flourish statuses to the GCDs which generate them. Fixes a bug where flourish gets synthed at the start of the fight.
> DNC - Flourish precast synth bugfix 

- src/data/ACTIONS/layers/patch5.4.ts
> Remove SPS scaling from EAs in 5.4 onwards

- src/parser/jobs/sam/modules/Shifu.ts
- src/reportSources/legacyFflogs/eventAdapter/speedStat.ts
1) SAM exposed a bug with the SpeedStatAdapter wherein if you have a speed modifier window (e.g. Shifu) that's unclosed at the end of the fight, and FFLogs didn't send an `encounterend` event for the fight, the unclosed window won't be considered at all because the "fight end time" was never set and was treated as 0.  Switched to use parser.pull + parser.duration to compute end time, like similar guards elsewhere in code and resolved that issue.
2) The Shifu cast time override didn't appropriately handle status refreshes and was generating overlapping / stacking Shifu windows which resulted in calculated recastTime for most skills quickly reaching 1.5s, thus resulting in very low ABC estimates and erroneous weaving dings after Iajutusu.
> fix: SAM not estimating GCD or ABC correctly

- src/parser/core/modules/Procs.tsx
- src/parser/jobs/blm/modules/Gauge.tsx
- src/parser/jobs/dnc/modules/Gauge.tsx
Deleting a few legacy support functions that are no longer necessary due to ongoing Analyser port work:
- Gauge state accessor in BLM Gauge
- Feather consumption accessor in DNC Gauge
- Proc usage accessor in core Procs
> Excise legacy functions - Part 1

- src/parser/jobs/blm/modules/Gauge.tsx
Missed this when porting to Analyser, woops
> fix: BLM - Drop overlooked fflogsToEpoch use

- src/parser/jobs/dnc/modules/Gauge.tsx
The `FINISHES` const is now ActionKey[], so I needed to map to the ID for the array of actions that don't generate Esprit. Adding a type to the array to ensure future oops like that don't happen
> Fix: DNC - Missed an ActionKey[].map in Gauge

- src/parser/jobs/pld/modules/Atonement.tsx
Since the fix to have `statusApply` events come through as stacking buffs build or decay, PLD's Atonement analyser has been unintentionally tripling the number of Atonements expected to be used. PR switches from incrementing gains on stack application, to checking for successful hits from Royal Authority.
I also went ahead and added tracking for overcap in the event that someone Royal Authorities again without having used all of the Atonement stacks, just in case we want to do something with it in the future.
Supercedes PR #1281
> Fix: PLD - Deal with stacking Atonement buff

- src/parser/jobs/mnk/modules/Forms.tsx
Downtime uses the Analyser system with correct timestamps, so correcting for fflogs timestamps isn't necessary anymore. Ignore the branch name.
> Remove deprecated timestamp corrections from MNK

- src/data/STATUSES/root/MNK.ts
- src/parser/jobs/mnk/modules/PerfectBalance.tsx
- src/parser/jobs/mnk/modules/constants.ts
Stacks remaining at the end of a window are 1 rather than 0, however we can't just subtract because it's possible for a legit stack to be left. Realistically it goes from 5->0 but the game prefers to do 6->1 and then just delete it. I have no idea how consistent this will even be, so I've changed the drop accounting to track the used GCDs and compare with the max stacks instead.
The constant is kinda silly, but `stacksApplied` is an optional field. Open to a cleaner way to do this tho, since I'm not sure if a null check is actually better in this case. This module is being rewritten in 6.0 since the entire skill is changing, so I'm not too fussed about expecting future changes in the 5.x branch anyway.
> Use actual GCD accounting instead of trusting status in PB drop math

- src/parser/core/modules/Checklist/Requirement.js
- src/parser/core/modules/Checklist/Rule.js
- src/parser/core/modules/Overheal.tsx
- src/parser/jobs/sch/index.js
- src/parser/jobs/sch/modules/Overheal.js
- src/parser/jobs/whm/index.js
- src/parser/jobs/whm/modules/Overheal.js
- src/reportSources/legacyFflogs/__tests__/__snapshots__/eventAdapter.ts.snap
- src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
- src/reportSources/legacyFflogs/eventAdapter/adapter.ts
- src/reportSources/legacyFflogs/eventAdapter/assignOverheal.ts
- src/reportSources/legacyFflogs/eventAdapter/deduplicateAoE.ts
As is tradition, I fiddled with the calculations on this port as well...
- Currently, the overheal module was only hooking the FFLogs `heal` events (the effect events in the new structure)
- The game, and thus FFLogs, does not consistently report `heal` events for heals that fully overheal (in general, it looks like any full-overheal on another target doesn't report an effect event)
- This caused our overheal numbers to be consistently low (significantly so if the player was doing a substantial amount of full-overheal)
- FFLogs's data tables currently treat all unmatched `calculatedheal` events as fully overheal (there's a possibility they could be ghosts from the target dying before the heal resolved, but that's a fairly infrequent occurrence)
- After this port, we will now also treat …
> port Core Overheal to Analyser

- src/parser/jobs/mnk/index.tsx
- src/parser/jobs/mnk/modules/TwinSnakes.tsx
I'm being cautious with this one due to how specific the scenario where we allow downtime is. We will remove the time between Twin dropping and being reapplied from the total fight time *if* there were exactly 2 GCDs post-PB before Twin was regained, and the 2nd one of those GCDs was Twin itself. This would normally account for bad downtime as well, if the user dropped Twin during RoF or something, so we have a secondary check that the time of the drop was after the time of PB dropping too. Very fiddly, but I think there's enough sanity checking here for it to be fine.
In testing, "good" players should go from 92-93% to their "real" value of 96-97%, while lesser skilled players will see a smaller increase or none at all, mostly around 1-2%.
> Account for planned downtime of Twin Snakes in checklist math

- src/reportSources/legacyFflogs/searchHandlers.ts
Title. Looks like the main site's API still has the data regardless of the URL change.
Resolves #1332
> Add CN TLD to search handler regex

- src/parser/core/modules/Gauge/Gauge.tsx
- src/parser/core/modules/Gauge/TimerGauge.ts
- src/parser/jobs/blm/modules/Gauge.tsx
- src/parser/jobs/dnc/modules/Gauge.tsx
- src/parser/jobs/drk/modules/Darkside.tsx
Also did a little bit of cleanup in core TimerGauge:
1. Now passes the TimestampHookArguments (the timestamp of the timeout) to onExpirationCallback consumers
2. Adjusted variable naming and documentation comments to indicate any fight downtime windows are valid, and some documentation of cases when you would prefer UTA downtime versus full fight downtime
3. Allow refresh and extend to specify whether the action should refresh/extend a gauge that wasn't previously running (to allow basic consumers like Darkside to just call extend always, as both their gauge extenders add 30 seconds regardless of whether the gauge was already running or not - you don't have to use a specific skill to initially start the gauge).
> port Darkside to core Gauge as a Timer Gauge

- src/parser/core/modules/RaidBuffs.ts
This just fixes an issue with Embolden (and any other stacked buff) not showing full duration in raid buffs.
> fixed issue with embolden only tracking final stack in raid buffs

- src/parser/jobs/blm/modules/RotationWatchdog.tsx
When I did the change to stop depending on ACTIONS in RotationWatchdog, I had to move the CYCLE_ERRORS definitions into the class, instead of being a const outside (probably reverting this in EW now that we have DataLink). One spot where the old CYCLE_ERRORS.NONE code was being referenced got missed when switching that to the NO_ERROR const object, which was causing the error code to end up undefined (side note to self, how to ensure type safety on that object...)
> BugFix - BLM - onComplete reprocessing of invuln cycles was breaking

- src/parser/jobs/blm/modules/Gauge.tsx
If the BLM happened to get the initial damage event of the log, and that event should've produced a gauge event (likely either setting AF or UI to 3), it wouldn't publish a `blmgauge` event because of how we were comparing current state vs. previous state all at relative timestamp of 0.
Now we'll make sure we have an initial null-Gauge state to compare against to keep this from happening (plus some re-ordering of operations to make this work).
> Bugfix: BLM - Fix gauge state tracking in case the BLM pulls

- .github/labeler.yml
Labels are created, colours to be updated once we have them from fflogs I guess. For now it's (conveniently role-accurate) GitHub default colours from when I created them. This PR is so the labeler action can properly tag the new jobs in Endwalker.
> Add RPR and SGE labeler config

- locale/en/messages.json
- src/parser/jobs/blm/changelog.tsx
- src/parser/jobs/blm/modules/AoEUsages.ts
- src/parser/jobs/blm/modules/Thunder.tsx
- Adds AoEUsages entries for [High] [Blizzard/Fire] II and Freeze
- Adjust AoEUsages entry for Flare since it's base potency is lower now 😢 
- Updates Thunder's clipping calculations for T3 since the status durations have been adjusted
> Endwalker - BLM - AoEUsages and Thunder changes
